/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminInviteRequestsDenyBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminInviteRequestsDenyBody1 {
  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("invite_request_id")
  private String inviteRequestId = null;

  public AdminInviteRequestsDenyBody1 teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * ID for the workspace where the invite request was made.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public AdminInviteRequestsDenyBody1 inviteRequestId(String inviteRequestId) {
    this.inviteRequestId = inviteRequestId;
    return this;
  }

   /**
   * ID of the request to invite.
   * @return inviteRequestId
  **/
  public String getInviteRequestId() {
    return inviteRequestId;
  }

  public void setInviteRequestId(String inviteRequestId) {
    this.inviteRequestId = inviteRequestId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminInviteRequestsDenyBody1 adminInviteRequestsDenyBody1 = (AdminInviteRequestsDenyBody1) o;
    return Objects.equals(this.teamId, adminInviteRequestsDenyBody1.teamId) &&
        Objects.equals(this.inviteRequestId, adminInviteRequestsDenyBody1.inviteRequestId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, inviteRequestId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminInviteRequestsDenyBody1 {\n");
    
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    inviteRequestId: ").append(toIndentedString(inviteRequestId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
