/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminConversationsSetTeamsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsSetTeamsBody {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("target_team_ids")
  private String targetTeamIds = null;

  @JsonProperty("org_channel")
  private Boolean orgChannel = null;

  public AdminConversationsSetTeamsBody channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The encoded &#x60;channel_id&#x60; to add or remove to workspaces.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public AdminConversationsSetTeamsBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The workspace to which the channel belongs. Omit this argument if the channel is a cross-workspace shared channel.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public AdminConversationsSetTeamsBody targetTeamIds(String targetTeamIds) {
    this.targetTeamIds = targetTeamIds;
    return this;
  }

   /**
   * A comma-separated list of workspaces to which the channel should be shared. Not required if the channel is being shared org-wide.
   * @return targetTeamIds
  **/
  public String getTargetTeamIds() {
    return targetTeamIds;
  }

  public void setTargetTeamIds(String targetTeamIds) {
    this.targetTeamIds = targetTeamIds;
  }

  public AdminConversationsSetTeamsBody orgChannel(Boolean orgChannel) {
    this.orgChannel = orgChannel;
    return this;
  }

   /**
   * True if channel has to be converted to an org channel
   * @return orgChannel
  **/
  public Boolean isOrgChannel() {
    return orgChannel;
  }

  public void setOrgChannel(Boolean orgChannel) {
    this.orgChannel = orgChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsSetTeamsBody adminConversationsSetTeamsBody = (AdminConversationsSetTeamsBody) o;
    return Objects.equals(this.channelId, adminConversationsSetTeamsBody.channelId) &&
        Objects.equals(this.teamId, adminConversationsSetTeamsBody.teamId) &&
        Objects.equals(this.targetTeamIds, adminConversationsSetTeamsBody.targetTeamIds) &&
        Objects.equals(this.orgChannel, adminConversationsSetTeamsBody.orgChannel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, teamId, targetTeamIds, orgChannel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsSetTeamsBody {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    targetTeamIds: ").append(toIndentedString(targetTeamIds)).append("\n");
    sb.append("    orgChannel: ").append(toIndentedString(orgChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
