/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminConversationsRestrictAccessAddGroupBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsRestrictAccessAddGroupBody {
  @JsonProperty("token")
  private String token = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("group_id")
  private String groupId = null;

  @JsonProperty("channel_id")
  private String channelId = null;

  public AdminConversationsRestrictAccessAddGroupBody token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Authentication token. Requires scope: &#x60;admin.conversations:write&#x60;
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public AdminConversationsRestrictAccessAddGroupBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The workspace where the channel exists. This argument is required for channels only tied to one workspace, and optional for channels that are shared across an organization.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public AdminConversationsRestrictAccessAddGroupBody groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-provider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the private channel.
   * @return groupId
  **/
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public AdminConversationsRestrictAccessAddGroupBody channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The channel to link this group to.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsRestrictAccessAddGroupBody adminConversationsRestrictAccessAddGroupBody = (AdminConversationsRestrictAccessAddGroupBody) o;
    return Objects.equals(this.token, adminConversationsRestrictAccessAddGroupBody.token) &&
        Objects.equals(this.teamId, adminConversationsRestrictAccessAddGroupBody.teamId) &&
        Objects.equals(this.groupId, adminConversationsRestrictAccessAddGroupBody.groupId) &&
        Objects.equals(this.channelId, adminConversationsRestrictAccessAddGroupBody.channelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, teamId, groupId, channelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsRestrictAccessAddGroupBody {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
