/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminUsersAssignBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminUsersAssignBody {
  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("user_id")
  private String userId = null;

  @JsonProperty("is_restricted")
  private Boolean isRestricted = null;

  @JsonProperty("is_ultra_restricted")
  private Boolean isUltraRestricted = null;

  @JsonProperty("channel_ids")
  private String channelIds = null;

  public AdminUsersAssignBody teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * The ID (&#x60;T1234&#x60;) of the workspace.
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public AdminUsersAssignBody userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The ID of the user to add to the workspace.
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public AdminUsersAssignBody isRestricted(Boolean isRestricted) {
    this.isRestricted = isRestricted;
    return this;
  }

   /**
   * True if user should be added to the workspace as a guest.
   * @return isRestricted
  **/
  public Boolean isIsRestricted() {
    return isRestricted;
  }

  public void setIsRestricted(Boolean isRestricted) {
    this.isRestricted = isRestricted;
  }

  public AdminUsersAssignBody isUltraRestricted(Boolean isUltraRestricted) {
    this.isUltraRestricted = isUltraRestricted;
    return this;
  }

   /**
   * True if user should be added to the workspace as a single-channel guest.
   * @return isUltraRestricted
  **/
  public Boolean isIsUltraRestricted() {
    return isUltraRestricted;
  }

  public void setIsUltraRestricted(Boolean isUltraRestricted) {
    this.isUltraRestricted = isUltraRestricted;
  }

  public AdminUsersAssignBody channelIds(String channelIds) {
    this.channelIds = channelIds;
    return this;
  }

   /**
   * Comma separated values of channel IDs to add user in the new workspace.
   * @return channelIds
  **/
  public String getChannelIds() {
    return channelIds;
  }

  public void setChannelIds(String channelIds) {
    this.channelIds = channelIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUsersAssignBody adminUsersAssignBody = (AdminUsersAssignBody) o;
    return Objects.equals(this.teamId, adminUsersAssignBody.teamId) &&
        Objects.equals(this.userId, adminUsersAssignBody.userId) &&
        Objects.equals(this.isRestricted, adminUsersAssignBody.isRestricted) &&
        Objects.equals(this.isUltraRestricted, adminUsersAssignBody.isUltraRestricted) &&
        Objects.equals(this.channelIds, adminUsersAssignBody.channelIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamId, userId, isRestricted, isUltraRestricted, channelIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUsersAssignBody {\n");
    
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    isRestricted: ").append(toIndentedString(isRestricted)).append("\n");
    sb.append("    isUltraRestricted: ").append(toIndentedString(isUltraRestricted)).append("\n");
    sb.append("    channelIds: ").append(toIndentedString(channelIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
