/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminConversationsDisconnectSharedBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsDisconnectSharedBody1 {
  @JsonProperty("channel_id")
  private String channelId = null;

  @JsonProperty("leaving_team_ids")
  private String leavingTeamIds = null;

  public AdminConversationsDisconnectSharedBody1 channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The channel to be disconnected from some workspaces.
   * @return channelId
  **/
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }

  public AdminConversationsDisconnectSharedBody1 leavingTeamIds(String leavingTeamIds) {
    this.leavingTeamIds = leavingTeamIds;
    return this;
  }

   /**
   * The team to be removed from the channel. Currently only a single team id can be specified.
   * @return leavingTeamIds
  **/
  public String getLeavingTeamIds() {
    return leavingTeamIds;
  }

  public void setLeavingTeamIds(String leavingTeamIds) {
    this.leavingTeamIds = leavingTeamIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsDisconnectSharedBody1 adminConversationsDisconnectSharedBody1 = (AdminConversationsDisconnectSharedBody1) o;
    return Objects.equals(this.channelId, adminConversationsDisconnectSharedBody1.channelId) &&
        Objects.equals(this.leavingTeamIds, adminConversationsDisconnectSharedBody1.leavingTeamIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelId, leavingTeamIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsDisconnectSharedBody1 {\n");
    
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("    leavingTeamIds: ").append(toIndentedString(leavingTeamIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
