/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.AdminConversationsGetConversationPrefsSchemaPrefs;

/**
 * Schema for successful response of admin.conversations.getConversationPrefs
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsGetConversationPrefsSchema {
  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("prefs")
  private AdminConversationsGetConversationPrefsSchemaPrefs prefs = null;

  public AdminConversationsGetConversationPrefsSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public AdminConversationsGetConversationPrefsSchema prefs(AdminConversationsGetConversationPrefsSchemaPrefs prefs) {
    this.prefs = prefs;
    return this;
  }

   /**
   * Get prefs
   * @return prefs
  **/
  public AdminConversationsGetConversationPrefsSchemaPrefs getPrefs() {
    return prefs;
  }

  public void setPrefs(AdminConversationsGetConversationPrefsSchemaPrefs prefs) {
    this.prefs = prefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsGetConversationPrefsSchema adminConversationsGetConversationPrefsSchema = (AdminConversationsGetConversationPrefsSchema) o;
    return Objects.equals(this.ok, adminConversationsGetConversationPrefsSchema.ok) &&
        Objects.equals(this.prefs, adminConversationsGetConversationPrefsSchema.prefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ok, prefs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsGetConversationPrefsSchema {\n");
    
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    prefs: ").append(toIndentedString(prefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
