/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for error response from admin.conversations.archive
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsArchiveErrorSchema {
  /**
   * Gets or Sets error
   */
  public enum ErrorEnum {
    FEATURE_NOT_ENABLED("feature_not_enabled"),
    CHANNEL_NOT_FOUND("channel_not_found"),
    CHANNEL_TYPE_NOT_SUPPORTED("channel_type_not_supported"),
    DEFAULT_ORG_WIDE_CHANNEL("default_org_wide_channel"),
    ALREADY_ARCHIVED("already_archived"),
    CANT_ARCHIVE_GENERAL("cant_archive_general"),
    RESTRICTED_ACTION("restricted_action"),
    COULD_NOT_ARCHIVE_CHANNEL("could_not_archive_channel");

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ErrorEnum fromValue(String input) {
      for (ErrorEnum b : ErrorEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("error")
  private ErrorEnum error = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  public AdminConversationsArchiveErrorSchema error(ErrorEnum error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public ErrorEnum getError() {
    return error;
  }

  public void setError(ErrorEnum error) {
    this.error = error;
  }

  public AdminConversationsArchiveErrorSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsArchiveErrorSchema adminConversationsArchiveErrorSchema = (AdminConversationsArchiveErrorSchema) o;
    return Objects.equals(this.error, adminConversationsArchiveErrorSchema.error) &&
        Objects.equals(this.ok, adminConversationsArchiveErrorSchema.ok);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, ok);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsArchiveErrorSchema {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
