/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AdminUsergroupsAddTeamsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminUsergroupsAddTeamsBody {
  @JsonProperty("usergroup_id")
  private String usergroupId = null;

  @JsonProperty("team_ids")
  private String teamIds = null;

  @JsonProperty("auto_provision")
  private Boolean autoProvision = null;

  public AdminUsergroupsAddTeamsBody usergroupId(String usergroupId) {
    this.usergroupId = usergroupId;
    return this;
  }

   /**
   * An encoded usergroup (IDP Group) ID.
   * @return usergroupId
  **/
  public String getUsergroupId() {
    return usergroupId;
  }

  public void setUsergroupId(String usergroupId) {
    this.usergroupId = usergroupId;
  }

  public AdminUsergroupsAddTeamsBody teamIds(String teamIds) {
    this.teamIds = teamIds;
    return this;
  }

   /**
   * A comma separated list of encoded team (workspace) IDs. Each workspace *MUST* belong to the organization associated with the token.
   * @return teamIds
  **/
  public String getTeamIds() {
    return teamIds;
  }

  public void setTeamIds(String teamIds) {
    this.teamIds = teamIds;
  }

  public AdminUsergroupsAddTeamsBody autoProvision(Boolean autoProvision) {
    this.autoProvision = autoProvision;
    return this;
  }

   /**
   * When &#x60;true&#x60;, this method automatically creates new workspace accounts for the IDP group members.
   * @return autoProvision
  **/
  public Boolean isAutoProvision() {
    return autoProvision;
  }

  public void setAutoProvision(Boolean autoProvision) {
    this.autoProvision = autoProvision;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUsergroupsAddTeamsBody adminUsergroupsAddTeamsBody = (AdminUsergroupsAddTeamsBody) o;
    return Objects.equals(this.usergroupId, adminUsergroupsAddTeamsBody.usergroupId) &&
        Objects.equals(this.teamIds, adminUsergroupsAddTeamsBody.teamIds) &&
        Objects.equals(this.autoProvision, adminUsergroupsAddTeamsBody.autoProvision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usergroupId, teamIds, autoProvision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUsergroupsAddTeamsBody {\n");
    
    sb.append("    usergroupId: ").append(toIndentedString(usergroupId)).append("\n");
    sb.append("    teamIds: ").append(toIndentedString(teamIds)).append("\n");
    sb.append("    autoProvision: ").append(toIndentedString(autoProvision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
