/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.AdminConversationsGetConversationPrefsSchemaPrefsCanThread;

/**
 * AdminConversationsGetConversationPrefsSchemaPrefs
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AdminConversationsGetConversationPrefsSchemaPrefs {
  @JsonProperty("can_thread")
  private AdminConversationsGetConversationPrefsSchemaPrefsCanThread canThread = null;

  @JsonProperty("who_can_post")
  private AdminConversationsGetConversationPrefsSchemaPrefsCanThread whoCanPost = null;

  public AdminConversationsGetConversationPrefsSchemaPrefs canThread(AdminConversationsGetConversationPrefsSchemaPrefsCanThread canThread) {
    this.canThread = canThread;
    return this;
  }

   /**
   * Get canThread
   * @return canThread
  **/
  public AdminConversationsGetConversationPrefsSchemaPrefsCanThread getCanThread() {
    return canThread;
  }

  public void setCanThread(AdminConversationsGetConversationPrefsSchemaPrefsCanThread canThread) {
    this.canThread = canThread;
  }

  public AdminConversationsGetConversationPrefsSchemaPrefs whoCanPost(AdminConversationsGetConversationPrefsSchemaPrefsCanThread whoCanPost) {
    this.whoCanPost = whoCanPost;
    return this;
  }

   /**
   * Get whoCanPost
   * @return whoCanPost
  **/
  public AdminConversationsGetConversationPrefsSchemaPrefsCanThread getWhoCanPost() {
    return whoCanPost;
  }

  public void setWhoCanPost(AdminConversationsGetConversationPrefsSchemaPrefsCanThread whoCanPost) {
    this.whoCanPost = whoCanPost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminConversationsGetConversationPrefsSchemaPrefs adminConversationsGetConversationPrefsSchemaPrefs = (AdminConversationsGetConversationPrefsSchemaPrefs) o;
    return Objects.equals(this.canThread, adminConversationsGetConversationPrefsSchemaPrefs.canThread) &&
        Objects.equals(this.whoCanPost, adminConversationsGetConversationPrefsSchemaPrefs.whoCanPost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canThread, whoCanPost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminConversationsGetConversationPrefsSchemaPrefs {\n");
    
    sb.append("    canThread: ").append(toIndentedString(canThread)).append("\n");
    sb.append("    whoCanPost: ").append(toIndentedString(whoCanPost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
