/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.ResourcesInInfoFromAppsPermissionsInfo;

import java.util.ArrayList;
import java.util.List;
/**
 * AppsPermissionsInfoSchemaInfoTeam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AppsPermissionsInfoSchemaInfoTeam {
  @JsonProperty("resources")
  private ResourcesInInfoFromAppsPermissionsInfo resources = null;

  @JsonProperty("scopes")
  private List<String> scopes = new ArrayList<>();

  public AppsPermissionsInfoSchemaInfoTeam resources(ResourcesInInfoFromAppsPermissionsInfo resources) {
    this.resources = resources;
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  public ResourcesInInfoFromAppsPermissionsInfo getResources() {
    return resources;
  }

  public void setResources(ResourcesInInfoFromAppsPermissionsInfo resources) {
    this.resources = resources;
  }

  public AppsPermissionsInfoSchemaInfoTeam scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public AppsPermissionsInfoSchemaInfoTeam addScopesItem(String scopesItem) {
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppsPermissionsInfoSchemaInfoTeam appsPermissionsInfoSchemaInfoTeam = (AppsPermissionsInfoSchemaInfoTeam) o;
    return Objects.equals(this.resources, appsPermissionsInfoSchemaInfoTeam.resources) &&
        Objects.equals(this.scopes, appsPermissionsInfoSchemaInfoTeam.scopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resources, scopes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppsPermissionsInfoSchemaInfoTeam {\n");
    
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
