/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.AppsPermissionsInfoSchemaInfoAppHome;
import com.slack.api.client.AppsPermissionsInfoSchemaInfoChannel;
import com.slack.api.client.AppsPermissionsInfoSchemaInfoTeam;

/**
 * AppsPermissionsInfoSchemaInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AppsPermissionsInfoSchemaInfo {
  @JsonProperty("app_home")
  private AppsPermissionsInfoSchemaInfoAppHome appHome = null;

  @JsonProperty("channel")
  private AppsPermissionsInfoSchemaInfoChannel channel = null;

  @JsonProperty("group")
  private AppsPermissionsInfoSchemaInfoChannel group = null;

  @JsonProperty("im")
  private AppsPermissionsInfoSchemaInfoChannel im = null;

  @JsonProperty("mpim")
  private AppsPermissionsInfoSchemaInfoChannel mpim = null;

  @JsonProperty("team")
  private AppsPermissionsInfoSchemaInfoTeam team = null;

  public AppsPermissionsInfoSchemaInfo appHome(AppsPermissionsInfoSchemaInfoAppHome appHome) {
    this.appHome = appHome;
    return this;
  }

   /**
   * Get appHome
   * @return appHome
  **/
  public AppsPermissionsInfoSchemaInfoAppHome getAppHome() {
    return appHome;
  }

  public void setAppHome(AppsPermissionsInfoSchemaInfoAppHome appHome) {
    this.appHome = appHome;
  }

  public AppsPermissionsInfoSchemaInfo channel(AppsPermissionsInfoSchemaInfoChannel channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  public AppsPermissionsInfoSchemaInfoChannel getChannel() {
    return channel;
  }

  public void setChannel(AppsPermissionsInfoSchemaInfoChannel channel) {
    this.channel = channel;
  }

  public AppsPermissionsInfoSchemaInfo group(AppsPermissionsInfoSchemaInfoChannel group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  public AppsPermissionsInfoSchemaInfoChannel getGroup() {
    return group;
  }

  public void setGroup(AppsPermissionsInfoSchemaInfoChannel group) {
    this.group = group;
  }

  public AppsPermissionsInfoSchemaInfo im(AppsPermissionsInfoSchemaInfoChannel im) {
    this.im = im;
    return this;
  }

   /**
   * Get im
   * @return im
  **/
  public AppsPermissionsInfoSchemaInfoChannel getIm() {
    return im;
  }

  public void setIm(AppsPermissionsInfoSchemaInfoChannel im) {
    this.im = im;
  }

  public AppsPermissionsInfoSchemaInfo mpim(AppsPermissionsInfoSchemaInfoChannel mpim) {
    this.mpim = mpim;
    return this;
  }

   /**
   * Get mpim
   * @return mpim
  **/
  public AppsPermissionsInfoSchemaInfoChannel getMpim() {
    return mpim;
  }

  public void setMpim(AppsPermissionsInfoSchemaInfoChannel mpim) {
    this.mpim = mpim;
  }

  public AppsPermissionsInfoSchemaInfo team(AppsPermissionsInfoSchemaInfoTeam team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  public AppsPermissionsInfoSchemaInfoTeam getTeam() {
    return team;
  }

  public void setTeam(AppsPermissionsInfoSchemaInfoTeam team) {
    this.team = team;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppsPermissionsInfoSchemaInfo appsPermissionsInfoSchemaInfo = (AppsPermissionsInfoSchemaInfo) o;
    return Objects.equals(this.appHome, appsPermissionsInfoSchemaInfo.appHome) &&
        Objects.equals(this.channel, appsPermissionsInfoSchemaInfo.channel) &&
        Objects.equals(this.group, appsPermissionsInfoSchemaInfo.group) &&
        Objects.equals(this.im, appsPermissionsInfoSchemaInfo.im) &&
        Objects.equals(this.mpim, appsPermissionsInfoSchemaInfo.mpim) &&
        Objects.equals(this.team, appsPermissionsInfoSchemaInfo.team);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appHome, channel, group, im, mpim, team);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppsPermissionsInfoSchemaInfo {\n");
    
    sb.append("    appHome: ").append(toIndentedString(appHome)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    im: ").append(toIndentedString(im)).append("\n");
    sb.append("    mpim: ").append(toIndentedString(mpim)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
