/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for successful response auth.test method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class AuthTestSuccessSchema {
  @JsonProperty("bot_id")
  private String botId = null;

  @JsonProperty("is_enterprise_install")
  private Boolean isEnterpriseInstall = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("team")
  private String team = null;

  @JsonProperty("team_id")
  private String teamId = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("user")
  private String user = null;

  @JsonProperty("user_id")
  private String userId = null;

  public AuthTestSuccessSchema botId(String botId) {
    this.botId = botId;
    return this;
  }

   /**
   * Get botId
   * @return botId
  **/
  public String getBotId() {
    return botId;
  }

  public void setBotId(String botId) {
    this.botId = botId;
  }

  public AuthTestSuccessSchema isEnterpriseInstall(Boolean isEnterpriseInstall) {
    this.isEnterpriseInstall = isEnterpriseInstall;
    return this;
  }

   /**
   * Get isEnterpriseInstall
   * @return isEnterpriseInstall
  **/
  public Boolean isIsEnterpriseInstall() {
    return isEnterpriseInstall;
  }

  public void setIsEnterpriseInstall(Boolean isEnterpriseInstall) {
    this.isEnterpriseInstall = isEnterpriseInstall;
  }

  public AuthTestSuccessSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public AuthTestSuccessSchema team(String team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  public String getTeam() {
    return team;
  }

  public void setTeam(String team) {
    this.team = team;
  }

  public AuthTestSuccessSchema teamId(String teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(String teamId) {
    this.teamId = teamId;
  }

  public AuthTestSuccessSchema url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public AuthTestSuccessSchema user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public AuthTestSuccessSchema userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthTestSuccessSchema authTestSuccessSchema = (AuthTestSuccessSchema) o;
    return Objects.equals(this.botId, authTestSuccessSchema.botId) &&
        Objects.equals(this.isEnterpriseInstall, authTestSuccessSchema.isEnterpriseInstall) &&
        Objects.equals(this.ok, authTestSuccessSchema.ok) &&
        Objects.equals(this.team, authTestSuccessSchema.team) &&
        Objects.equals(this.teamId, authTestSuccessSchema.teamId) &&
        Objects.equals(this.url, authTestSuccessSchema.url) &&
        Objects.equals(this.user, authTestSuccessSchema.user) &&
        Objects.equals(this.userId, authTestSuccessSchema.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(botId, isEnterpriseInstall, ok, team, teamId, url, user, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthTestSuccessSchema {\n");
    
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    isEnterpriseInstall: ").append(toIndentedString(isEnterpriseInstall)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
