/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CallsParticipantsAddBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class CallsParticipantsAddBody {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("users")
  private String users = null;

  public CallsParticipantsAddBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * &#x60;id&#x60; returned by the [&#x60;calls.add&#x60;](/methods/calls.add) method.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CallsParticipantsAddBody users(String users) {
    this.users = users;
    return this;
  }

   /**
   * The list of users to add as participants in the Call. [Read more on how to specify users here](/apis/calls#users).
   * @return users
  **/
  public String getUsers() {
    return users;
  }

  public void setUsers(String users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallsParticipantsAddBody callsParticipantsAddBody = (CallsParticipantsAddBody) o;
    return Objects.equals(this.id, callsParticipantsAddBody.id) &&
        Objects.equals(this.users, callsParticipantsAddBody.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallsParticipantsAddBody {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
