/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Schema for successful response from chat.scheduledMessages.list method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatScheduledMessagesListSchema {
  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("response_metadata")
  private Object responseMetadata = null;

  @JsonProperty("scheduled_messages")
  private List<Object> scheduledMessages = new ArrayList<>();

  public ChatScheduledMessagesListSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public ChatScheduledMessagesListSchema responseMetadata(Object responseMetadata) {
    this.responseMetadata = responseMetadata;
    return this;
  }

   /**
   * Get responseMetadata
   * @return responseMetadata
  **/
  public Object getResponseMetadata() {
    return responseMetadata;
  }

  public void setResponseMetadata(Object responseMetadata) {
    this.responseMetadata = responseMetadata;
  }

  public ChatScheduledMessagesListSchema scheduledMessages(List<Object> scheduledMessages) {
    this.scheduledMessages = scheduledMessages;
    return this;
  }

  public ChatScheduledMessagesListSchema addScheduledMessagesItem(Object scheduledMessagesItem) {
    this.scheduledMessages.add(scheduledMessagesItem);
    return this;
  }

   /**
   * Get scheduledMessages
   * @return scheduledMessages
  **/
  public List<Object> getScheduledMessages() {
    return scheduledMessages;
  }

  public void setScheduledMessages(List<Object> scheduledMessages) {
    this.scheduledMessages = scheduledMessages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatScheduledMessagesListSchema chatScheduledMessagesListSchema = (ChatScheduledMessagesListSchema) o;
    return Objects.equals(this.ok, chatScheduledMessagesListSchema.ok) &&
        Objects.equals(this.responseMetadata, chatScheduledMessagesListSchema.responseMetadata) &&
        Objects.equals(this.scheduledMessages, chatScheduledMessagesListSchema.scheduledMessages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ok, responseMetadata, scheduledMessages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatScheduledMessagesListSchema {\n");
    
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    responseMetadata: ").append(toIndentedString(responseMetadata)).append("\n");
    sb.append("    scheduledMessages: ").append(toIndentedString(scheduledMessages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
