/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatPostMessageBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatPostMessageBody {
  @JsonProperty("as_user")
  private String asUser = null;

  @JsonProperty("attachments")
  private String attachments = null;

  @JsonProperty("blocks")
  private String blocks = null;

  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("icon_emoji")
  private String iconEmoji = null;

  @JsonProperty("icon_url")
  private String iconUrl = null;

  @JsonProperty("link_names")
  private Boolean linkNames = null;

  @JsonProperty("mrkdwn")
  private Boolean mrkdwn = null;

  @JsonProperty("parse")
  private String parse = null;

  @JsonProperty("reply_broadcast")
  private Boolean replyBroadcast = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("thread_ts")
  private String threadTs = null;

  @JsonProperty("unfurl_links")
  private Boolean unfurlLinks = null;

  @JsonProperty("unfurl_media")
  private Boolean unfurlMedia = null;

  @JsonProperty("username")
  private String username = null;

  public ChatPostMessageBody asUser(String asUser) {
    this.asUser = asUser;
    return this;
  }

   /**
   * Pass true to post the message as the authed user, instead of as a bot. Defaults to false. See [authorship](#authorship) below.
   * @return asUser
  **/
  public String getAsUser() {
    return asUser;
  }

  public void setAsUser(String asUser) {
    this.asUser = asUser;
  }

  public ChatPostMessageBody attachments(String attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * A JSON-based array of structured attachments, presented as a URL-encoded string.
   * @return attachments
  **/
  public String getAttachments() {
    return attachments;
  }

  public void setAttachments(String attachments) {
    this.attachments = attachments;
  }

  public ChatPostMessageBody blocks(String blocks) {
    this.blocks = blocks;
    return this;
  }

   /**
   * A JSON-based array of structured blocks, presented as a URL-encoded string.
   * @return blocks
  **/
  public String getBlocks() {
    return blocks;
  }

  public void setBlocks(String blocks) {
    this.blocks = blocks;
  }

  public ChatPostMessageBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel, private group, or IM channel to send message to. Can be an encoded ID, or a name. See [below](#channels) for more details.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatPostMessageBody iconEmoji(String iconEmoji) {
    this.iconEmoji = iconEmoji;
    return this;
  }

   /**
   * Emoji to use as the icon for this message. Overrides &#x60;icon_url&#x60;. Must be used in conjunction with &#x60;as_user&#x60; set to &#x60;false&#x60;, otherwise ignored. See [authorship](#authorship) below.
   * @return iconEmoji
  **/
  public String getIconEmoji() {
    return iconEmoji;
  }

  public void setIconEmoji(String iconEmoji) {
    this.iconEmoji = iconEmoji;
  }

  public ChatPostMessageBody iconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

   /**
   * URL to an image to use as the icon for this message. Must be used in conjunction with &#x60;as_user&#x60; set to false, otherwise ignored. See [authorship](#authorship) below.
   * @return iconUrl
  **/
  public String getIconUrl() {
    return iconUrl;
  }

  public void setIconUrl(String iconUrl) {
    this.iconUrl = iconUrl;
  }

  public ChatPostMessageBody linkNames(Boolean linkNames) {
    this.linkNames = linkNames;
    return this;
  }

   /**
   * Find and link channel names and usernames.
   * @return linkNames
  **/
  public Boolean isLinkNames() {
    return linkNames;
  }

  public void setLinkNames(Boolean linkNames) {
    this.linkNames = linkNames;
  }

  public ChatPostMessageBody mrkdwn(Boolean mrkdwn) {
    this.mrkdwn = mrkdwn;
    return this;
  }

   /**
   * Disable Slack markup parsing by setting to &#x60;false&#x60;. Enabled by default.
   * @return mrkdwn
  **/
  public Boolean isMrkdwn() {
    return mrkdwn;
  }

  public void setMrkdwn(Boolean mrkdwn) {
    this.mrkdwn = mrkdwn;
  }

  public ChatPostMessageBody parse(String parse) {
    this.parse = parse;
    return this;
  }

   /**
   * Change how messages are treated. Defaults to &#x60;none&#x60;. See [below](#formatting).
   * @return parse
  **/
  public String getParse() {
    return parse;
  }

  public void setParse(String parse) {
    this.parse = parse;
  }

  public ChatPostMessageBody replyBroadcast(Boolean replyBroadcast) {
    this.replyBroadcast = replyBroadcast;
    return this;
  }

   /**
   * Used in conjunction with &#x60;thread_ts&#x60; and indicates whether reply should be made visible to everyone in the channel or conversation. Defaults to &#x60;false&#x60;.
   * @return replyBroadcast
  **/
  public Boolean isReplyBroadcast() {
    return replyBroadcast;
  }

  public void setReplyBroadcast(Boolean replyBroadcast) {
    this.replyBroadcast = replyBroadcast;
  }

  public ChatPostMessageBody text(String text) {
    this.text = text;
    return this;
  }

   /**
   * How this field works and whether it is required depends on other fields you use in your API call. [See below](#text_usage) for more detail.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ChatPostMessageBody threadTs(String threadTs) {
    this.threadTs = threadTs;
    return this;
  }

   /**
   * Provide another message&#x27;s &#x60;ts&#x60; value to make this message a reply. Avoid using a reply&#x27;s &#x60;ts&#x60; value; use its parent instead.
   * @return threadTs
  **/
  public String getThreadTs() {
    return threadTs;
  }

  public void setThreadTs(String threadTs) {
    this.threadTs = threadTs;
  }

  public ChatPostMessageBody unfurlLinks(Boolean unfurlLinks) {
    this.unfurlLinks = unfurlLinks;
    return this;
  }

   /**
   * Pass true to enable unfurling of primarily text-based content.
   * @return unfurlLinks
  **/
  public Boolean isUnfurlLinks() {
    return unfurlLinks;
  }

  public void setUnfurlLinks(Boolean unfurlLinks) {
    this.unfurlLinks = unfurlLinks;
  }

  public ChatPostMessageBody unfurlMedia(Boolean unfurlMedia) {
    this.unfurlMedia = unfurlMedia;
    return this;
  }

   /**
   * Pass false to disable unfurling of media content.
   * @return unfurlMedia
  **/
  public Boolean isUnfurlMedia() {
    return unfurlMedia;
  }

  public void setUnfurlMedia(Boolean unfurlMedia) {
    this.unfurlMedia = unfurlMedia;
  }

  public ChatPostMessageBody username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Set your bot&#x27;s user name. Must be used in conjunction with &#x60;as_user&#x60; set to false, otherwise ignored. See [authorship](#authorship) below.
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatPostMessageBody chatPostMessageBody = (ChatPostMessageBody) o;
    return Objects.equals(this.asUser, chatPostMessageBody.asUser) &&
        Objects.equals(this.attachments, chatPostMessageBody.attachments) &&
        Objects.equals(this.blocks, chatPostMessageBody.blocks) &&
        Objects.equals(this.channel, chatPostMessageBody.channel) &&
        Objects.equals(this.iconEmoji, chatPostMessageBody.iconEmoji) &&
        Objects.equals(this.iconUrl, chatPostMessageBody.iconUrl) &&
        Objects.equals(this.linkNames, chatPostMessageBody.linkNames) &&
        Objects.equals(this.mrkdwn, chatPostMessageBody.mrkdwn) &&
        Objects.equals(this.parse, chatPostMessageBody.parse) &&
        Objects.equals(this.replyBroadcast, chatPostMessageBody.replyBroadcast) &&
        Objects.equals(this.text, chatPostMessageBody.text) &&
        Objects.equals(this.threadTs, chatPostMessageBody.threadTs) &&
        Objects.equals(this.unfurlLinks, chatPostMessageBody.unfurlLinks) &&
        Objects.equals(this.unfurlMedia, chatPostMessageBody.unfurlMedia) &&
        Objects.equals(this.username, chatPostMessageBody.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asUser, attachments, blocks, channel, iconEmoji, iconUrl, linkNames, mrkdwn, parse, replyBroadcast, text, threadTs, unfurlLinks, unfurlMedia, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatPostMessageBody {\n");
    
    sb.append("    asUser: ").append(toIndentedString(asUser)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    iconEmoji: ").append(toIndentedString(iconEmoji)).append("\n");
    sb.append("    iconUrl: ").append(toIndentedString(iconUrl)).append("\n");
    sb.append("    linkNames: ").append(toIndentedString(linkNames)).append("\n");
    sb.append("    mrkdwn: ").append(toIndentedString(mrkdwn)).append("\n");
    sb.append("    parse: ").append(toIndentedString(parse)).append("\n");
    sb.append("    replyBroadcast: ").append(toIndentedString(replyBroadcast)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    threadTs: ").append(toIndentedString(threadTs)).append("\n");
    sb.append("    unfurlLinks: ").append(toIndentedString(unfurlLinks)).append("\n");
    sb.append("    unfurlMedia: ").append(toIndentedString(unfurlMedia)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
