/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatUpdateBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatUpdateBody {
  @JsonProperty("as_user")
  private String asUser = null;

  @JsonProperty("attachments")
  private String attachments = null;

  @JsonProperty("blocks")
  private String blocks = null;

  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("link_names")
  private String linkNames = null;

  @JsonProperty("parse")
  private String parse = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("ts")
  private String ts = null;

  public ChatUpdateBody asUser(String asUser) {
    this.asUser = asUser;
    return this;
  }

   /**
   * Pass true to update the message as the authed user. [Bot users](/bot-users) in this context are considered authed users.
   * @return asUser
  **/
  public String getAsUser() {
    return asUser;
  }

  public void setAsUser(String asUser) {
    this.asUser = asUser;
  }

  public ChatUpdateBody attachments(String attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * A JSON-based array of structured attachments, presented as a URL-encoded string. This field is required when not presenting &#x60;text&#x60;. If you don&#x27;t include this field, the message&#x27;s previous &#x60;attachments&#x60; will be retained. To remove previous &#x60;attachments&#x60;, include an empty array for this field.
   * @return attachments
  **/
  public String getAttachments() {
    return attachments;
  }

  public void setAttachments(String attachments) {
    this.attachments = attachments;
  }

  public ChatUpdateBody blocks(String blocks) {
    this.blocks = blocks;
    return this;
  }

   /**
   * A JSON-based array of [structured blocks](/block-kit/building), presented as a URL-encoded string. If you don&#x27;t include this field, the message&#x27;s previous &#x60;blocks&#x60; will be retained. To remove previous &#x60;blocks&#x60;, include an empty array for this field.
   * @return blocks
  **/
  public String getBlocks() {
    return blocks;
  }

  public void setBlocks(String blocks) {
    this.blocks = blocks;
  }

  public ChatUpdateBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel containing the message to be updated.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatUpdateBody linkNames(String linkNames) {
    this.linkNames = linkNames;
    return this;
  }

   /**
   * Find and link channel names and usernames. Defaults to &#x60;none&#x60;. If you do not specify a value for this field, the original value set for the message will be overwritten with the default, &#x60;none&#x60;.
   * @return linkNames
  **/
  public String getLinkNames() {
    return linkNames;
  }

  public void setLinkNames(String linkNames) {
    this.linkNames = linkNames;
  }

  public ChatUpdateBody parse(String parse) {
    this.parse = parse;
    return this;
  }

   /**
   * Change how messages are treated. Defaults to &#x60;client&#x60;, unlike &#x60;chat.postMessage&#x60;. Accepts either &#x60;none&#x60; or &#x60;full&#x60;. If you do not specify a value for this field, the original value set for the message will be overwritten with the default, &#x60;client&#x60;.
   * @return parse
  **/
  public String getParse() {
    return parse;
  }

  public void setParse(String parse) {
    this.parse = parse;
  }

  public ChatUpdateBody text(String text) {
    this.text = text;
    return this;
  }

   /**
   * New text for the message, using the [default formatting rules](/reference/surfaces/formatting). It&#x27;s not required when presenting &#x60;blocks&#x60; or &#x60;attachments&#x60;.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ChatUpdateBody ts(String ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp of the message to be updated.
   * @return ts
  **/
  public String getTs() {
    return ts;
  }

  public void setTs(String ts) {
    this.ts = ts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatUpdateBody chatUpdateBody = (ChatUpdateBody) o;
    return Objects.equals(this.asUser, chatUpdateBody.asUser) &&
        Objects.equals(this.attachments, chatUpdateBody.attachments) &&
        Objects.equals(this.blocks, chatUpdateBody.blocks) &&
        Objects.equals(this.channel, chatUpdateBody.channel) &&
        Objects.equals(this.linkNames, chatUpdateBody.linkNames) &&
        Objects.equals(this.parse, chatUpdateBody.parse) &&
        Objects.equals(this.text, chatUpdateBody.text) &&
        Objects.equals(this.ts, chatUpdateBody.ts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asUser, attachments, blocks, channel, linkNames, parse, text, ts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatUpdateBody {\n");
    
    sb.append("    asUser: ").append(toIndentedString(asUser)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    linkNames: ").append(toIndentedString(linkNames)).append("\n");
    sb.append("    parse: ").append(toIndentedString(parse)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
