/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatDeleteScheduledMessageBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatDeleteScheduledMessageBody {
  @JsonProperty("as_user")
  private Boolean asUser = null;

  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("scheduled_message_id")
  private String scheduledMessageId = null;

  public ChatDeleteScheduledMessageBody asUser(Boolean asUser) {
    this.asUser = asUser;
    return this;
  }

   /**
   * Pass true to delete the message as the authed user with &#x60;chat:write:user&#x60; scope. [Bot users](/bot-users) in this context are considered authed users. If unused or false, the message will be deleted with &#x60;chat:write:bot&#x60; scope.
   * @return asUser
  **/
  public Boolean isAsUser() {
    return asUser;
  }

  public void setAsUser(Boolean asUser) {
    this.asUser = asUser;
  }

  public ChatDeleteScheduledMessageBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The channel the scheduled_message is posting to
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatDeleteScheduledMessageBody scheduledMessageId(String scheduledMessageId) {
    this.scheduledMessageId = scheduledMessageId;
    return this;
  }

   /**
   * &#x60;scheduled_message_id&#x60; returned from call to chat.scheduleMessage
   * @return scheduledMessageId
  **/
  public String getScheduledMessageId() {
    return scheduledMessageId;
  }

  public void setScheduledMessageId(String scheduledMessageId) {
    this.scheduledMessageId = scheduledMessageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatDeleteScheduledMessageBody chatDeleteScheduledMessageBody = (ChatDeleteScheduledMessageBody) o;
    return Objects.equals(this.asUser, chatDeleteScheduledMessageBody.asUser) &&
        Objects.equals(this.channel, chatDeleteScheduledMessageBody.channel) &&
        Objects.equals(this.scheduledMessageId, chatDeleteScheduledMessageBody.scheduledMessageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asUser, channel, scheduledMessageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatDeleteScheduledMessageBody {\n");
    
    sb.append("    asUser: ").append(toIndentedString(asUser)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    scheduledMessageId: ").append(toIndentedString(scheduledMessageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
