/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * ChatDeleteBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatDeleteBody {
  @JsonProperty("ts")
  private BigDecimal ts = null;

  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("as_user")
  private Boolean asUser = null;

  public ChatDeleteBody ts(BigDecimal ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Timestamp of the message to be deleted.
   * @return ts
  **/
  public BigDecimal getTs() {
    return ts;
  }

  public void setTs(BigDecimal ts) {
    this.ts = ts;
  }

  public ChatDeleteBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel containing the message to be deleted.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatDeleteBody asUser(Boolean asUser) {
    this.asUser = asUser;
    return this;
  }

   /**
   * Pass true to delete the message as the authed user with &#x60;chat:write:user&#x60; scope. [Bot users](/bot-users) in this context are considered authed users. If unused or false, the message will be deleted with &#x60;chat:write:bot&#x60; scope.
   * @return asUser
  **/
  public Boolean isAsUser() {
    return asUser;
  }

  public void setAsUser(Boolean asUser) {
    this.asUser = asUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatDeleteBody chatDeleteBody = (ChatDeleteBody) o;
    return Objects.equals(this.ts, chatDeleteBody.ts) &&
        Objects.equals(this.channel, chatDeleteBody.channel) &&
        Objects.equals(this.asUser, chatDeleteBody.asUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ts, channel, asUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatDeleteBody {\n");
    
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    asUser: ").append(toIndentedString(asUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
