/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for successful response of chat.scheduleMessage method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatScheduleMessageSuccessSchema {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("message")
  private Object message = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("post_at")
  private Integer postAt = null;

  @JsonProperty("scheduled_message_id")
  private String scheduledMessageId = null;

  public ChatScheduleMessageSuccessSchema channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatScheduleMessageSuccessSchema message(Object message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  public Object getMessage() {
    return message;
  }

  public void setMessage(Object message) {
    this.message = message;
  }

  public ChatScheduleMessageSuccessSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public ChatScheduleMessageSuccessSchema postAt(Integer postAt) {
    this.postAt = postAt;
    return this;
  }

   /**
   * Get postAt
   * @return postAt
  **/
  public Integer getPostAt() {
    return postAt;
  }

  public void setPostAt(Integer postAt) {
    this.postAt = postAt;
  }

  public ChatScheduleMessageSuccessSchema scheduledMessageId(String scheduledMessageId) {
    this.scheduledMessageId = scheduledMessageId;
    return this;
  }

   /**
   * Get scheduledMessageId
   * @return scheduledMessageId
  **/
  public String getScheduledMessageId() {
    return scheduledMessageId;
  }

  public void setScheduledMessageId(String scheduledMessageId) {
    this.scheduledMessageId = scheduledMessageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatScheduleMessageSuccessSchema chatScheduleMessageSuccessSchema = (ChatScheduleMessageSuccessSchema) o;
    return Objects.equals(this.channel, chatScheduleMessageSuccessSchema.channel) &&
        Objects.equals(this.message, chatScheduleMessageSuccessSchema.message) &&
        Objects.equals(this.ok, chatScheduleMessageSuccessSchema.ok) &&
        Objects.equals(this.postAt, chatScheduleMessageSuccessSchema.postAt) &&
        Objects.equals(this.scheduledMessageId, chatScheduleMessageSuccessSchema.scheduledMessageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, message, ok, postAt, scheduledMessageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatScheduleMessageSuccessSchema {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    scheduledMessageId: ").append(toIndentedString(scheduledMessageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
