/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * ChatScheduleMessageBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatScheduleMessageBody1 {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("post_at")
  private String postAt = null;

  @JsonProperty("parse")
  private String parse = null;

  @JsonProperty("as_user")
  private Boolean asUser = null;

  @JsonProperty("link_names")
  private Boolean linkNames = null;

  @JsonProperty("attachments")
  private String attachments = null;

  @JsonProperty("blocks")
  private String blocks = null;

  @JsonProperty("unfurl_links")
  private Boolean unfurlLinks = null;

  @JsonProperty("unfurl_media")
  private Boolean unfurlMedia = null;

  @JsonProperty("thread_ts")
  private BigDecimal threadTs = null;

  @JsonProperty("reply_broadcast")
  private Boolean replyBroadcast = null;

  public ChatScheduleMessageBody1 channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel, private group, or DM channel to send message to. Can be an encoded ID, or a name. See [below](#channels) for more details.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ChatScheduleMessageBody1 text(String text) {
    this.text = text;
    return this;
  }

   /**
   * How this field works and whether it is required depends on other fields you use in your API call. [See below](#text_usage) for more detail.
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ChatScheduleMessageBody1 postAt(String postAt) {
    this.postAt = postAt;
    return this;
  }

   /**
   * Unix EPOCH timestamp of time in future to send the message.
   * @return postAt
  **/
  public String getPostAt() {
    return postAt;
  }

  public void setPostAt(String postAt) {
    this.postAt = postAt;
  }

  public ChatScheduleMessageBody1 parse(String parse) {
    this.parse = parse;
    return this;
  }

   /**
   * Change how messages are treated. Defaults to &#x60;none&#x60;. See [chat.postMessage](chat.postMessage#formatting).
   * @return parse
  **/
  public String getParse() {
    return parse;
  }

  public void setParse(String parse) {
    this.parse = parse;
  }

  public ChatScheduleMessageBody1 asUser(Boolean asUser) {
    this.asUser = asUser;
    return this;
  }

   /**
   * Pass true to post the message as the authed user, instead of as a bot. Defaults to false. See [chat.postMessage](chat.postMessage#authorship).
   * @return asUser
  **/
  public Boolean isAsUser() {
    return asUser;
  }

  public void setAsUser(Boolean asUser) {
    this.asUser = asUser;
  }

  public ChatScheduleMessageBody1 linkNames(Boolean linkNames) {
    this.linkNames = linkNames;
    return this;
  }

   /**
   * Find and link channel names and usernames.
   * @return linkNames
  **/
  public Boolean isLinkNames() {
    return linkNames;
  }

  public void setLinkNames(Boolean linkNames) {
    this.linkNames = linkNames;
  }

  public ChatScheduleMessageBody1 attachments(String attachments) {
    this.attachments = attachments;
    return this;
  }

   /**
   * A JSON-based array of structured attachments, presented as a URL-encoded string.
   * @return attachments
  **/
  public String getAttachments() {
    return attachments;
  }

  public void setAttachments(String attachments) {
    this.attachments = attachments;
  }

  public ChatScheduleMessageBody1 blocks(String blocks) {
    this.blocks = blocks;
    return this;
  }

   /**
   * A JSON-based array of structured blocks, presented as a URL-encoded string.
   * @return blocks
  **/
  public String getBlocks() {
    return blocks;
  }

  public void setBlocks(String blocks) {
    this.blocks = blocks;
  }

  public ChatScheduleMessageBody1 unfurlLinks(Boolean unfurlLinks) {
    this.unfurlLinks = unfurlLinks;
    return this;
  }

   /**
   * Pass true to enable unfurling of primarily text-based content.
   * @return unfurlLinks
  **/
  public Boolean isUnfurlLinks() {
    return unfurlLinks;
  }

  public void setUnfurlLinks(Boolean unfurlLinks) {
    this.unfurlLinks = unfurlLinks;
  }

  public ChatScheduleMessageBody1 unfurlMedia(Boolean unfurlMedia) {
    this.unfurlMedia = unfurlMedia;
    return this;
  }

   /**
   * Pass false to disable unfurling of media content.
   * @return unfurlMedia
  **/
  public Boolean isUnfurlMedia() {
    return unfurlMedia;
  }

  public void setUnfurlMedia(Boolean unfurlMedia) {
    this.unfurlMedia = unfurlMedia;
  }

  public ChatScheduleMessageBody1 threadTs(BigDecimal threadTs) {
    this.threadTs = threadTs;
    return this;
  }

   /**
   * Provide another message&#x27;s &#x60;ts&#x60; value to make this message a reply. Avoid using a reply&#x27;s &#x60;ts&#x60; value; use its parent instead.
   * @return threadTs
  **/
  public BigDecimal getThreadTs() {
    return threadTs;
  }

  public void setThreadTs(BigDecimal threadTs) {
    this.threadTs = threadTs;
  }

  public ChatScheduleMessageBody1 replyBroadcast(Boolean replyBroadcast) {
    this.replyBroadcast = replyBroadcast;
    return this;
  }

   /**
   * Used in conjunction with &#x60;thread_ts&#x60; and indicates whether reply should be made visible to everyone in the channel or conversation. Defaults to &#x60;false&#x60;.
   * @return replyBroadcast
  **/
  public Boolean isReplyBroadcast() {
    return replyBroadcast;
  }

  public void setReplyBroadcast(Boolean replyBroadcast) {
    this.replyBroadcast = replyBroadcast;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatScheduleMessageBody1 chatScheduleMessageBody1 = (ChatScheduleMessageBody1) o;
    return Objects.equals(this.channel, chatScheduleMessageBody1.channel) &&
        Objects.equals(this.text, chatScheduleMessageBody1.text) &&
        Objects.equals(this.postAt, chatScheduleMessageBody1.postAt) &&
        Objects.equals(this.parse, chatScheduleMessageBody1.parse) &&
        Objects.equals(this.asUser, chatScheduleMessageBody1.asUser) &&
        Objects.equals(this.linkNames, chatScheduleMessageBody1.linkNames) &&
        Objects.equals(this.attachments, chatScheduleMessageBody1.attachments) &&
        Objects.equals(this.blocks, chatScheduleMessageBody1.blocks) &&
        Objects.equals(this.unfurlLinks, chatScheduleMessageBody1.unfurlLinks) &&
        Objects.equals(this.unfurlMedia, chatScheduleMessageBody1.unfurlMedia) &&
        Objects.equals(this.threadTs, chatScheduleMessageBody1.threadTs) &&
        Objects.equals(this.replyBroadcast, chatScheduleMessageBody1.replyBroadcast);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, text, postAt, parse, asUser, linkNames, attachments, blocks, unfurlLinks, unfurlMedia, threadTs, replyBroadcast);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatScheduleMessageBody1 {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    postAt: ").append(toIndentedString(postAt)).append("\n");
    sb.append("    parse: ").append(toIndentedString(parse)).append("\n");
    sb.append("    asUser: ").append(toIndentedString(asUser)).append("\n");
    sb.append("    linkNames: ").append(toIndentedString(linkNames)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    unfurlLinks: ").append(toIndentedString(unfurlLinks)).append("\n");
    sb.append("    unfurlMedia: ").append(toIndentedString(unfurlMedia)).append("\n");
    sb.append("    threadTs: ").append(toIndentedString(threadTs)).append("\n");
    sb.append("    replyBroadcast: ").append(toIndentedString(replyBroadcast)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
