/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for error response chat.update method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ChatUpdateErrorSchema {
  @JsonProperty("callstack")
  private String callstack = null;

  /**
   * Gets or Sets error
   */
  public enum ErrorEnum {
    MESSAGE_NOT_FOUND("message_not_found"),
    CANT_UPDATE_MESSAGE("cant_update_message"),
    CHANNEL_NOT_FOUND("channel_not_found"),
    EDIT_WINDOW_CLOSED("edit_window_closed"),
    MSG_TOO_LONG("msg_too_long"),
    TOO_MANY_ATTACHMENTS("too_many_attachments"),
    RATE_LIMITED("rate_limited"),
    NO_TEXT("no_text"),
    NOT_AUTHED("not_authed"),
    INVALID_AUTH("invalid_auth"),
    ACCOUNT_INACTIVE("account_inactive"),
    TOKEN_REVOKED("token_revoked"),
    NO_PERMISSION("no_permission"),
    INVALID_ARG_NAME("invalid_arg_name"),
    INVALID_ARRAY_ARG("invalid_array_arg"),
    INVALID_CHARSET("invalid_charset"),
    INVALID_FORM_DATA("invalid_form_data"),
    INVALID_POST_TYPE("invalid_post_type"),
    MISSING_POST_TYPE("missing_post_type"),
    REQUEST_TIMEOUT("request_timeout"),
    INVALID_JSON("invalid_json"),
    JSON_NOT_OBJECT("json_not_object"),
    UPGRADE_REQUIRED("upgrade_required"),
    FATAL_ERROR("fatal_error"),
    IS_INACTIVE("is_inactive");

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ErrorEnum fromValue(String input) {
      for (ErrorEnum b : ErrorEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("error")
  private ErrorEnum error = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  public ChatUpdateErrorSchema callstack(String callstack) {
    this.callstack = callstack;
    return this;
  }

   /**
   * Note: PHP callstack is only visible in dev/qa
   * @return callstack
  **/
  public String getCallstack() {
    return callstack;
  }

  public void setCallstack(String callstack) {
    this.callstack = callstack;
  }

  public ChatUpdateErrorSchema error(ErrorEnum error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public ErrorEnum getError() {
    return error;
  }

  public void setError(ErrorEnum error) {
    this.error = error;
  }

  public ChatUpdateErrorSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatUpdateErrorSchema chatUpdateErrorSchema = (ChatUpdateErrorSchema) o;
    return Objects.equals(this.callstack, chatUpdateErrorSchema.callstack) &&
        Objects.equals(this.error, chatUpdateErrorSchema.error) &&
        Objects.equals(this.ok, chatUpdateErrorSchema.ok);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callstack, error, ok);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatUpdateErrorSchema {\n");
    
    sb.append("    callstack: ").append(toIndentedString(callstack)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
