/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConversationsOpenBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsOpenBody {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("users")
  private String users = null;

  @JsonProperty("return_im")
  private Boolean returnIm = null;

  public ConversationsOpenBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Resume a conversation by supplying an &#x60;im&#x60; or &#x60;mpim&#x60;&#x27;s ID. Or provide the &#x60;users&#x60; field instead.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ConversationsOpenBody users(String users) {
    this.users = users;
    return this;
  }

   /**
   * Comma separated lists of users. If only one user is included, this creates a 1:1 DM.  The ordering of the users is preserved whenever a multi-person direct message is returned. Supply a &#x60;channel&#x60; when not supplying &#x60;users&#x60;.
   * @return users
  **/
  public String getUsers() {
    return users;
  }

  public void setUsers(String users) {
    this.users = users;
  }

  public ConversationsOpenBody returnIm(Boolean returnIm) {
    this.returnIm = returnIm;
    return this;
  }

   /**
   * Boolean, indicates you want the full IM channel definition in the response.
   * @return returnIm
  **/
  public Boolean isReturnIm() {
    return returnIm;
  }

  public void setReturnIm(Boolean returnIm) {
    this.returnIm = returnIm;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsOpenBody conversationsOpenBody = (ConversationsOpenBody) o;
    return Objects.equals(this.channel, conversationsOpenBody.channel) &&
        Objects.equals(this.users, conversationsOpenBody.users) &&
        Objects.equals(this.returnIm, conversationsOpenBody.returnIm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, users, returnIm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsOpenBody {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    returnIm: ").append(toIndentedString(returnIm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
