/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for error response from conversations.create method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsCreateErrorSchema {
  @JsonProperty("callstack")
  private String callstack = null;

  @JsonProperty("detail")
  private String detail = null;

  /**
   * Gets or Sets error
   */
  public enum ErrorEnum {
    METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE("method_not_supported_for_channel_type"),
    MISSING_SCOPE("missing_scope"),
    NAME_TAKEN("name_taken"),
    RESTRICTED_ACTION("restricted_action"),
    NO_CHANNEL("no_channel"),
    INVALID_NAME_REQUIRED("invalid_name_required"),
    INVALID_NAME_PUNCTUATION("invalid_name_punctuation"),
    INVALID_NAME_MAXLENGTH("invalid_name_maxlength"),
    INVALID_NAME_SPECIALS("invalid_name_specials"),
    INVALID_NAME("invalid_name"),
    NOT_AUTHED("not_authed"),
    INVALID_AUTH("invalid_auth"),
    ACCOUNT_INACTIVE("account_inactive"),
    USER_IS_BOT("user_is_bot"),
    USER_IS_RESTRICTED("user_is_restricted"),
    INVALID_ARG_NAME("invalid_arg_name"),
    INVALID_ARRAY_ARG("invalid_array_arg"),
    INVALID_CHARSET("invalid_charset"),
    INVALID_FORM_DATA("invalid_form_data"),
    INVALID_POST_TYPE("invalid_post_type"),
    MISSING_POST_TYPE("missing_post_type"),
    TEAM_ADDED_TO_ORG("team_added_to_org"),
    INVALID_JSON("invalid_json"),
    JSON_NOT_OBJECT("json_not_object"),
    REQUEST_TIMEOUT("request_timeout"),
    UPGRADE_REQUIRED("upgrade_required");

    private String value;

    ErrorEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ErrorEnum fromValue(String input) {
      for (ErrorEnum b : ErrorEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("error")
  private ErrorEnum error = null;

  @JsonProperty("needed")
  private String needed = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("provided")
  private String provided = null;

  public ConversationsCreateErrorSchema callstack(String callstack) {
    this.callstack = callstack;
    return this;
  }

   /**
   * Note: PHP callstack is only visible in dev/qa
   * @return callstack
  **/
  public String getCallstack() {
    return callstack;
  }

  public void setCallstack(String callstack) {
    this.callstack = callstack;
  }

  public ConversationsCreateErrorSchema detail(String detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public ConversationsCreateErrorSchema error(ErrorEnum error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  public ErrorEnum getError() {
    return error;
  }

  public void setError(ErrorEnum error) {
    this.error = error;
  }

  public ConversationsCreateErrorSchema needed(String needed) {
    this.needed = needed;
    return this;
  }

   /**
   * Get needed
   * @return needed
  **/
  public String getNeeded() {
    return needed;
  }

  public void setNeeded(String needed) {
    this.needed = needed;
  }

  public ConversationsCreateErrorSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public ConversationsCreateErrorSchema provided(String provided) {
    this.provided = provided;
    return this;
  }

   /**
   * Get provided
   * @return provided
  **/
  public String getProvided() {
    return provided;
  }

  public void setProvided(String provided) {
    this.provided = provided;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsCreateErrorSchema conversationsCreateErrorSchema = (ConversationsCreateErrorSchema) o;
    return Objects.equals(this.callstack, conversationsCreateErrorSchema.callstack) &&
        Objects.equals(this.detail, conversationsCreateErrorSchema.detail) &&
        Objects.equals(this.error, conversationsCreateErrorSchema.error) &&
        Objects.equals(this.needed, conversationsCreateErrorSchema.needed) &&
        Objects.equals(this.ok, conversationsCreateErrorSchema.ok) &&
        Objects.equals(this.provided, conversationsCreateErrorSchema.provided);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callstack, detail, error, needed, ok, provided);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsCreateErrorSchema {\n");
    
    sb.append("    callstack: ").append(toIndentedString(callstack)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    needed: ").append(toIndentedString(needed)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    provided: ").append(toIndentedString(provided)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
