/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * ConversationsMarkBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsMarkBody1 {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("ts")
  private BigDecimal ts = null;

  public ConversationsMarkBody1 channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel or conversation to set the read cursor for.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ConversationsMarkBody1 ts(BigDecimal ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Unique identifier of message you want marked as most recently seen in this conversation.
   * @return ts
  **/
  public BigDecimal getTs() {
    return ts;
  }

  public void setTs(BigDecimal ts) {
    this.ts = ts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsMarkBody1 conversationsMarkBody1 = (ConversationsMarkBody1) o;
    return Objects.equals(this.channel, conversationsMarkBody1.channel) &&
        Objects.equals(this.ts, conversationsMarkBody1.ts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, ts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsMarkBody1 {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
