/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for successful response conversations.close method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsCloseSuccessSchema {
  @JsonProperty("already_closed")
  private Boolean alreadyClosed = null;

  @JsonProperty("no_op")
  private Boolean noOp = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  public ConversationsCloseSuccessSchema alreadyClosed(Boolean alreadyClosed) {
    this.alreadyClosed = alreadyClosed;
    return this;
  }

   /**
   * Get alreadyClosed
   * @return alreadyClosed
  **/
  public Boolean isAlreadyClosed() {
    return alreadyClosed;
  }

  public void setAlreadyClosed(Boolean alreadyClosed) {
    this.alreadyClosed = alreadyClosed;
  }

  public ConversationsCloseSuccessSchema noOp(Boolean noOp) {
    this.noOp = noOp;
    return this;
  }

   /**
   * Get noOp
   * @return noOp
  **/
  public Boolean isNoOp() {
    return noOp;
  }

  public void setNoOp(Boolean noOp) {
    this.noOp = noOp;
  }

  public ConversationsCloseSuccessSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsCloseSuccessSchema conversationsCloseSuccessSchema = (ConversationsCloseSuccessSchema) o;
    return Objects.equals(this.alreadyClosed, conversationsCloseSuccessSchema.alreadyClosed) &&
        Objects.equals(this.noOp, conversationsCloseSuccessSchema.noOp) &&
        Objects.equals(this.ok, conversationsCloseSuccessSchema.ok);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alreadyClosed, noOp, ok);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsCloseSuccessSchema {\n");
    
    sb.append("    alreadyClosed: ").append(toIndentedString(alreadyClosed)).append("\n");
    sb.append("    noOp: ").append(toIndentedString(noOp)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
