/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.ResponseMetadata;

import java.util.List;
/**
 * Schema for successful response from conversations.join method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsJoinSuccessSchema {
  @JsonProperty("channel")
  private List channel = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("response_metadata")
  private ResponseMetadata responseMetadata = null;

  @JsonProperty("warning")
  private String warning = null;

  public ConversationsJoinSuccessSchema channel(List channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  public List getChannel() {
    return channel;
  }

  public void setChannel(List channel) {
    this.channel = channel;
  }

  public ConversationsJoinSuccessSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public ConversationsJoinSuccessSchema responseMetadata(ResponseMetadata responseMetadata) {
    this.responseMetadata = responseMetadata;
    return this;
  }

   /**
   * Get responseMetadata
   * @return responseMetadata
  **/
  public ResponseMetadata getResponseMetadata() {
    return responseMetadata;
  }

  public void setResponseMetadata(ResponseMetadata responseMetadata) {
    this.responseMetadata = responseMetadata;
  }

  public ConversationsJoinSuccessSchema warning(String warning) {
    this.warning = warning;
    return this;
  }

   /**
   * Get warning
   * @return warning
  **/
  public String getWarning() {
    return warning;
  }

  public void setWarning(String warning) {
    this.warning = warning;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsJoinSuccessSchema conversationsJoinSuccessSchema = (ConversationsJoinSuccessSchema) o;
    return Objects.equals(this.channel, conversationsJoinSuccessSchema.channel) &&
        Objects.equals(this.ok, conversationsJoinSuccessSchema.ok) &&
        Objects.equals(this.responseMetadata, conversationsJoinSuccessSchema.responseMetadata) &&
        Objects.equals(this.warning, conversationsJoinSuccessSchema.warning);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, ok, responseMetadata, warning);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsJoinSuccessSchema {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    responseMetadata: ").append(toIndentedString(responseMetadata)).append("\n");
    sb.append("    warning: ").append(toIndentedString(warning)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
