/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConversationsInviteBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ConversationsInviteBody {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("users")
  private String users = null;

  public ConversationsInviteBody channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * The ID of the public or private channel to invite user(s) to.
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public ConversationsInviteBody users(String users) {
    this.users = users;
    return this;
  }

   /**
   * A comma separated list of user IDs. Up to 1000 users may be listed.
   * @return users
  **/
  public String getUsers() {
    return users;
  }

  public void setUsers(String users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationsInviteBody conversationsInviteBody = (ConversationsInviteBody) o;
    return Objects.equals(this.channel, conversationsInviteBody.channel) &&
        Objects.equals(this.users, conversationsInviteBody.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationsInviteBody {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
