/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for successful response from dnd.endSnooze method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class DndEndSnoozeSchema {
  @JsonProperty("dnd_enabled")
  private Boolean dndEnabled = null;

  @JsonProperty("next_dnd_end_ts")
  private Integer nextDndEndTs = null;

  @JsonProperty("next_dnd_start_ts")
  private Integer nextDndStartTs = null;

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("snooze_enabled")
  private Boolean snoozeEnabled = null;

  public DndEndSnoozeSchema dndEnabled(Boolean dndEnabled) {
    this.dndEnabled = dndEnabled;
    return this;
  }

   /**
   * Get dndEnabled
   * @return dndEnabled
  **/
  public Boolean isDndEnabled() {
    return dndEnabled;
  }

  public void setDndEnabled(Boolean dndEnabled) {
    this.dndEnabled = dndEnabled;
  }

  public DndEndSnoozeSchema nextDndEndTs(Integer nextDndEndTs) {
    this.nextDndEndTs = nextDndEndTs;
    return this;
  }

   /**
   * Get nextDndEndTs
   * @return nextDndEndTs
  **/
  public Integer getNextDndEndTs() {
    return nextDndEndTs;
  }

  public void setNextDndEndTs(Integer nextDndEndTs) {
    this.nextDndEndTs = nextDndEndTs;
  }

  public DndEndSnoozeSchema nextDndStartTs(Integer nextDndStartTs) {
    this.nextDndStartTs = nextDndStartTs;
    return this;
  }

   /**
   * Get nextDndStartTs
   * @return nextDndStartTs
  **/
  public Integer getNextDndStartTs() {
    return nextDndStartTs;
  }

  public void setNextDndStartTs(Integer nextDndStartTs) {
    this.nextDndStartTs = nextDndStartTs;
  }

  public DndEndSnoozeSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public DndEndSnoozeSchema snoozeEnabled(Boolean snoozeEnabled) {
    this.snoozeEnabled = snoozeEnabled;
    return this;
  }

   /**
   * Get snoozeEnabled
   * @return snoozeEnabled
  **/
  public Boolean isSnoozeEnabled() {
    return snoozeEnabled;
  }

  public void setSnoozeEnabled(Boolean snoozeEnabled) {
    this.snoozeEnabled = snoozeEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DndEndSnoozeSchema dndEndSnoozeSchema = (DndEndSnoozeSchema) o;
    return Objects.equals(this.dndEnabled, dndEndSnoozeSchema.dndEnabled) &&
        Objects.equals(this.nextDndEndTs, dndEndSnoozeSchema.nextDndEndTs) &&
        Objects.equals(this.nextDndStartTs, dndEndSnoozeSchema.nextDndStartTs) &&
        Objects.equals(this.ok, dndEndSnoozeSchema.ok) &&
        Objects.equals(this.snoozeEnabled, dndEndSnoozeSchema.snoozeEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dndEnabled, nextDndEndTs, nextDndStartTs, ok, snoozeEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DndEndSnoozeSchema {\n");
    
    sb.append("    dndEnabled: ").append(toIndentedString(dndEnabled)).append("\n");
    sb.append("    nextDndEndTs: ").append(toIndentedString(nextDndEndTs)).append("\n");
    sb.append("    nextDndStartTs: ").append(toIndentedString(nextDndStartTs)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    snoozeEnabled: ").append(toIndentedString(snoozeEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
