/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema for successful response from dnd.setSnooze method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class DndSetSnoozeSchema {
  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("snooze_enabled")
  private Boolean snoozeEnabled = null;

  @JsonProperty("snooze_endtime")
  private Integer snoozeEndtime = null;

  @JsonProperty("snooze_remaining")
  private Integer snoozeRemaining = null;

  public DndSetSnoozeSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public DndSetSnoozeSchema snoozeEnabled(Boolean snoozeEnabled) {
    this.snoozeEnabled = snoozeEnabled;
    return this;
  }

   /**
   * Get snoozeEnabled
   * @return snoozeEnabled
  **/
  public Boolean isSnoozeEnabled() {
    return snoozeEnabled;
  }

  public void setSnoozeEnabled(Boolean snoozeEnabled) {
    this.snoozeEnabled = snoozeEnabled;
  }

  public DndSetSnoozeSchema snoozeEndtime(Integer snoozeEndtime) {
    this.snoozeEndtime = snoozeEndtime;
    return this;
  }

   /**
   * Get snoozeEndtime
   * @return snoozeEndtime
  **/
  public Integer getSnoozeEndtime() {
    return snoozeEndtime;
  }

  public void setSnoozeEndtime(Integer snoozeEndtime) {
    this.snoozeEndtime = snoozeEndtime;
  }

  public DndSetSnoozeSchema snoozeRemaining(Integer snoozeRemaining) {
    this.snoozeRemaining = snoozeRemaining;
    return this;
  }

   /**
   * Get snoozeRemaining
   * @return snoozeRemaining
  **/
  public Integer getSnoozeRemaining() {
    return snoozeRemaining;
  }

  public void setSnoozeRemaining(Integer snoozeRemaining) {
    this.snoozeRemaining = snoozeRemaining;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DndSetSnoozeSchema dndSetSnoozeSchema = (DndSetSnoozeSchema) o;
    return Objects.equals(this.ok, dndSetSnoozeSchema.ok) &&
        Objects.equals(this.snoozeEnabled, dndSetSnoozeSchema.snoozeEnabled) &&
        Objects.equals(this.snoozeEndtime, dndSetSnoozeSchema.snoozeEndtime) &&
        Objects.equals(this.snoozeRemaining, dndSetSnoozeSchema.snoozeRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ok, snoozeEnabled, snoozeEndtime, snoozeRemaining);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DndSetSnoozeSchema {\n");
    
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    snoozeEnabled: ").append(toIndentedString(snoozeEnabled)).append("\n");
    sb.append("    snoozeEndtime: ").append(toIndentedString(snoozeEndtime)).append("\n");
    sb.append("    snoozeRemaining: ").append(toIndentedString(snoozeRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
