/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FilesRemoteRemoveBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class FilesRemoteRemoveBody {
  @JsonProperty("token")
  private String token = null;

  @JsonProperty("file")
  private String file = null;

  @JsonProperty("external_id")
  private String externalId = null;

  public FilesRemoteRemoveBody token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Authentication token. Requires scope: &#x60;remote_files:write&#x60;
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public FilesRemoteRemoveBody file(String file) {
    this.file = file;
    return this;
  }

   /**
   * Specify a file by providing its ID.
   * @return file
  **/
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public FilesRemoteRemoveBody externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Creator defined GUID for the file.
   * @return externalId
  **/
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilesRemoteRemoveBody filesRemoteRemoveBody = (FilesRemoteRemoveBody) o;
    return Objects.equals(this.token, filesRemoteRemoveBody.token) &&
        Objects.equals(this.file, filesRemoteRemoveBody.file) &&
        Objects.equals(this.externalId, filesRemoteRemoveBody.externalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, file, externalId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilesRemoteRemoveBody {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
