/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FilesRemoteUpdateBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class FilesRemoteUpdateBody {
  @JsonProperty("token")
  private String token = null;

  @JsonProperty("file")
  private String file = null;

  @JsonProperty("external_id")
  private String externalId = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("filetype")
  private String filetype = null;

  @JsonProperty("external_url")
  private String externalUrl = null;

  @JsonProperty("preview_image")
  private String previewImage = null;

  @JsonProperty("indexable_file_contents")
  private String indexableFileContents = null;

  public FilesRemoteUpdateBody token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Authentication token. Requires scope: &#x60;remote_files:write&#x60;
   * @return token
  **/
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public FilesRemoteUpdateBody file(String file) {
    this.file = file;
    return this;
  }

   /**
   * Specify a file by providing its ID.
   * @return file
  **/
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public FilesRemoteUpdateBody externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Creator defined GUID for the file.
   * @return externalId
  **/
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public FilesRemoteUpdateBody title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the file being shared.
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public FilesRemoteUpdateBody filetype(String filetype) {
    this.filetype = filetype;
    return this;
  }

   /**
   * type of file
   * @return filetype
  **/
  public String getFiletype() {
    return filetype;
  }

  public void setFiletype(String filetype) {
    this.filetype = filetype;
  }

  public FilesRemoteUpdateBody externalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
    return this;
  }

   /**
   * URL of the remote file.
   * @return externalUrl
  **/
  public String getExternalUrl() {
    return externalUrl;
  }

  public void setExternalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
  }

  public FilesRemoteUpdateBody previewImage(String previewImage) {
    this.previewImage = previewImage;
    return this;
  }

   /**
   * Preview of the document via &#x60;multipart/form-data&#x60;.
   * @return previewImage
  **/
  public String getPreviewImage() {
    return previewImage;
  }

  public void setPreviewImage(String previewImage) {
    this.previewImage = previewImage;
  }

  public FilesRemoteUpdateBody indexableFileContents(String indexableFileContents) {
    this.indexableFileContents = indexableFileContents;
    return this;
  }

   /**
   * File containing contents that can be used to improve searchability for the remote file.
   * @return indexableFileContents
  **/
  public String getIndexableFileContents() {
    return indexableFileContents;
  }

  public void setIndexableFileContents(String indexableFileContents) {
    this.indexableFileContents = indexableFileContents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilesRemoteUpdateBody filesRemoteUpdateBody = (FilesRemoteUpdateBody) o;
    return Objects.equals(this.token, filesRemoteUpdateBody.token) &&
        Objects.equals(this.file, filesRemoteUpdateBody.file) &&
        Objects.equals(this.externalId, filesRemoteUpdateBody.externalId) &&
        Objects.equals(this.title, filesRemoteUpdateBody.title) &&
        Objects.equals(this.filetype, filesRemoteUpdateBody.filetype) &&
        Objects.equals(this.externalUrl, filesRemoteUpdateBody.externalUrl) &&
        Objects.equals(this.previewImage, filesRemoteUpdateBody.previewImage) &&
        Objects.equals(this.indexableFileContents, filesRemoteUpdateBody.indexableFileContents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, file, externalId, title, filetype, externalUrl, previewImage, indexableFileContents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilesRemoteUpdateBody {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    filetype: ").append(toIndentedString(filetype)).append("\n");
    sb.append("    externalUrl: ").append(toIndentedString(externalUrl)).append("\n");
    sb.append("    previewImage: ").append(toIndentedString(previewImage)).append("\n");
    sb.append("    indexableFileContents: ").append(toIndentedString(indexableFileContents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
