/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * ObjsChannel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ObjsChannel {
  @JsonProperty("accepted_user")
  private String acceptedUser = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("creator")
  private String creator = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("is_archived")
  private Boolean isArchived = null;

  @JsonProperty("is_channel")
  private Boolean isChannel = null;

  @JsonProperty("is_frozen")
  private Boolean isFrozen = null;

  @JsonProperty("is_general")
  private Boolean isGeneral = null;

  @JsonProperty("is_member")
  private Boolean isMember = null;

  @JsonProperty("is_moved")
  private Integer isMoved = null;

  @JsonProperty("is_mpim")
  private Boolean isMpim = null;

  @JsonProperty("is_non_threadable")
  private Boolean isNonThreadable = null;

  @JsonProperty("is_org_shared")
  private Boolean isOrgShared = null;

  @JsonProperty("is_pending_ext_shared")
  private Boolean isPendingExtShared = null;

  @JsonProperty("is_private")
  private Boolean isPrivate = null;

  @JsonProperty("is_read_only")
  private Boolean isReadOnly = null;

  @JsonProperty("is_shared")
  private Boolean isShared = null;

  @JsonProperty("is_thread_only")
  private Boolean isThreadOnly = null;

  @JsonProperty("last_read")
  private String lastRead = null;

  @JsonProperty("latest")
  private Object latest = null;

  @JsonProperty("members")
  private List<String> members = new ArrayList<>();

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("name_normalized")
  private String nameNormalized = null;

  @JsonProperty("num_members")
  private Integer numMembers = null;

  @JsonProperty("pending_shared")
  private List<String> pendingShared = null;

  @JsonProperty("previous_names")
  private List<String> previousNames = null;

  @JsonProperty("priority")
  private BigDecimal priority = null;

  @JsonProperty("purpose")
  private Object purpose = null;

  @JsonProperty("topic")
  private Object topic = null;

  @JsonProperty("unlinked")
  private Integer unlinked = null;

  @JsonProperty("unread_count")
  private Integer unreadCount = null;

  @JsonProperty("unread_count_display")
  private Integer unreadCountDisplay = null;

  public ObjsChannel acceptedUser(String acceptedUser) {
    this.acceptedUser = acceptedUser;
    return this;
  }

   /**
   * Get acceptedUser
   * @return acceptedUser
  **/
  public String getAcceptedUser() {
    return acceptedUser;
  }

  public void setAcceptedUser(String acceptedUser) {
    this.acceptedUser = acceptedUser;
  }

  public ObjsChannel created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public ObjsChannel creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public ObjsChannel id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ObjsChannel isArchived(Boolean isArchived) {
    this.isArchived = isArchived;
    return this;
  }

   /**
   * Get isArchived
   * @return isArchived
  **/
  public Boolean isIsArchived() {
    return isArchived;
  }

  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }

  public ObjsChannel isChannel(Boolean isChannel) {
    this.isChannel = isChannel;
    return this;
  }

   /**
   * Get isChannel
   * @return isChannel
  **/
  public Boolean isIsChannel() {
    return isChannel;
  }

  public void setIsChannel(Boolean isChannel) {
    this.isChannel = isChannel;
  }

  public ObjsChannel isFrozen(Boolean isFrozen) {
    this.isFrozen = isFrozen;
    return this;
  }

   /**
   * Get isFrozen
   * @return isFrozen
  **/
  public Boolean isIsFrozen() {
    return isFrozen;
  }

  public void setIsFrozen(Boolean isFrozen) {
    this.isFrozen = isFrozen;
  }

  public ObjsChannel isGeneral(Boolean isGeneral) {
    this.isGeneral = isGeneral;
    return this;
  }

   /**
   * Get isGeneral
   * @return isGeneral
  **/
  public Boolean isIsGeneral() {
    return isGeneral;
  }

  public void setIsGeneral(Boolean isGeneral) {
    this.isGeneral = isGeneral;
  }

  public ObjsChannel isMember(Boolean isMember) {
    this.isMember = isMember;
    return this;
  }

   /**
   * Get isMember
   * @return isMember
  **/
  public Boolean isIsMember() {
    return isMember;
  }

  public void setIsMember(Boolean isMember) {
    this.isMember = isMember;
  }

  public ObjsChannel isMoved(Integer isMoved) {
    this.isMoved = isMoved;
    return this;
  }

   /**
   * Get isMoved
   * @return isMoved
  **/
  public Integer getIsMoved() {
    return isMoved;
  }

  public void setIsMoved(Integer isMoved) {
    this.isMoved = isMoved;
  }

  public ObjsChannel isMpim(Boolean isMpim) {
    this.isMpim = isMpim;
    return this;
  }

   /**
   * Get isMpim
   * @return isMpim
  **/
  public Boolean isIsMpim() {
    return isMpim;
  }

  public void setIsMpim(Boolean isMpim) {
    this.isMpim = isMpim;
  }

  public ObjsChannel isNonThreadable(Boolean isNonThreadable) {
    this.isNonThreadable = isNonThreadable;
    return this;
  }

   /**
   * Get isNonThreadable
   * @return isNonThreadable
  **/
  public Boolean isIsNonThreadable() {
    return isNonThreadable;
  }

  public void setIsNonThreadable(Boolean isNonThreadable) {
    this.isNonThreadable = isNonThreadable;
  }

  public ObjsChannel isOrgShared(Boolean isOrgShared) {
    this.isOrgShared = isOrgShared;
    return this;
  }

   /**
   * Get isOrgShared
   * @return isOrgShared
  **/
  public Boolean isIsOrgShared() {
    return isOrgShared;
  }

  public void setIsOrgShared(Boolean isOrgShared) {
    this.isOrgShared = isOrgShared;
  }

  public ObjsChannel isPendingExtShared(Boolean isPendingExtShared) {
    this.isPendingExtShared = isPendingExtShared;
    return this;
  }

   /**
   * Get isPendingExtShared
   * @return isPendingExtShared
  **/
  public Boolean isIsPendingExtShared() {
    return isPendingExtShared;
  }

  public void setIsPendingExtShared(Boolean isPendingExtShared) {
    this.isPendingExtShared = isPendingExtShared;
  }

  public ObjsChannel isPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Get isPrivate
   * @return isPrivate
  **/
  public Boolean isIsPrivate() {
    return isPrivate;
  }

  public void setIsPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
  }

  public ObjsChannel isReadOnly(Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
    return this;
  }

   /**
   * Get isReadOnly
   * @return isReadOnly
  **/
  public Boolean isIsReadOnly() {
    return isReadOnly;
  }

  public void setIsReadOnly(Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
  }

  public ObjsChannel isShared(Boolean isShared) {
    this.isShared = isShared;
    return this;
  }

   /**
   * Get isShared
   * @return isShared
  **/
  public Boolean isIsShared() {
    return isShared;
  }

  public void setIsShared(Boolean isShared) {
    this.isShared = isShared;
  }

  public ObjsChannel isThreadOnly(Boolean isThreadOnly) {
    this.isThreadOnly = isThreadOnly;
    return this;
  }

   /**
   * Get isThreadOnly
   * @return isThreadOnly
  **/
  public Boolean isIsThreadOnly() {
    return isThreadOnly;
  }

  public void setIsThreadOnly(Boolean isThreadOnly) {
    this.isThreadOnly = isThreadOnly;
  }

  public ObjsChannel lastRead(String lastRead) {
    this.lastRead = lastRead;
    return this;
  }

   /**
   * Get lastRead
   * @return lastRead
  **/
  public String getLastRead() {
    return lastRead;
  }

  public void setLastRead(String lastRead) {
    this.lastRead = lastRead;
  }

  public ObjsChannel latest(Object latest) {
    this.latest = latest;
    return this;
  }

   /**
   * Get latest
   * @return latest
  **/
  public Object getLatest() {
    return latest;
  }

  public void setLatest(Object latest) {
    this.latest = latest;
  }

  public ObjsChannel members(List<String> members) {
    this.members = members;
    return this;
  }

  public ObjsChannel addMembersItem(String membersItem) {
    this.members.add(membersItem);
    return this;
  }

   /**
   * Get members
   * @return members
  **/
  public List<String> getMembers() {
    return members;
  }

  public void setMembers(List<String> members) {
    this.members = members;
  }

  public ObjsChannel name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObjsChannel nameNormalized(String nameNormalized) {
    this.nameNormalized = nameNormalized;
    return this;
  }

   /**
   * Get nameNormalized
   * @return nameNormalized
  **/
  public String getNameNormalized() {
    return nameNormalized;
  }

  public void setNameNormalized(String nameNormalized) {
    this.nameNormalized = nameNormalized;
  }

  public ObjsChannel numMembers(Integer numMembers) {
    this.numMembers = numMembers;
    return this;
  }

   /**
   * Get numMembers
   * @return numMembers
  **/
  public Integer getNumMembers() {
    return numMembers;
  }

  public void setNumMembers(Integer numMembers) {
    this.numMembers = numMembers;
  }

  public ObjsChannel pendingShared(List<String> pendingShared) {
    this.pendingShared = pendingShared;
    return this;
  }

  public ObjsChannel addPendingSharedItem(String pendingSharedItem) {
    if (this.pendingShared == null) {
      this.pendingShared = new ArrayList<>();
    }
    this.pendingShared.add(pendingSharedItem);
    return this;
  }

   /**
   * Get pendingShared
   * @return pendingShared
  **/
  public List<String> getPendingShared() {
    return pendingShared;
  }

  public void setPendingShared(List<String> pendingShared) {
    this.pendingShared = pendingShared;
  }

  public ObjsChannel previousNames(List<String> previousNames) {
    this.previousNames = previousNames;
    return this;
  }

  public ObjsChannel addPreviousNamesItem(String previousNamesItem) {
    if (this.previousNames == null) {
      this.previousNames = new ArrayList<>();
    }
    this.previousNames.add(previousNamesItem);
    return this;
  }

   /**
   * Get previousNames
   * @return previousNames
  **/
  public List<String> getPreviousNames() {
    return previousNames;
  }

  public void setPreviousNames(List<String> previousNames) {
    this.previousNames = previousNames;
  }

  public ObjsChannel priority(BigDecimal priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  public BigDecimal getPriority() {
    return priority;
  }

  public void setPriority(BigDecimal priority) {
    this.priority = priority;
  }

  public ObjsChannel purpose(Object purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  public Object getPurpose() {
    return purpose;
  }

  public void setPurpose(Object purpose) {
    this.purpose = purpose;
  }

  public ObjsChannel topic(Object topic) {
    this.topic = topic;
    return this;
  }

   /**
   * Get topic
   * @return topic
  **/
  public Object getTopic() {
    return topic;
  }

  public void setTopic(Object topic) {
    this.topic = topic;
  }

  public ObjsChannel unlinked(Integer unlinked) {
    this.unlinked = unlinked;
    return this;
  }

   /**
   * Get unlinked
   * @return unlinked
  **/
  public Integer getUnlinked() {
    return unlinked;
  }

  public void setUnlinked(Integer unlinked) {
    this.unlinked = unlinked;
  }

  public ObjsChannel unreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
    return this;
  }

   /**
   * Get unreadCount
   * @return unreadCount
  **/
  public Integer getUnreadCount() {
    return unreadCount;
  }

  public void setUnreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
  }

  public ObjsChannel unreadCountDisplay(Integer unreadCountDisplay) {
    this.unreadCountDisplay = unreadCountDisplay;
    return this;
  }

   /**
   * Get unreadCountDisplay
   * @return unreadCountDisplay
  **/
  public Integer getUnreadCountDisplay() {
    return unreadCountDisplay;
  }

  public void setUnreadCountDisplay(Integer unreadCountDisplay) {
    this.unreadCountDisplay = unreadCountDisplay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjsChannel objsChannel = (ObjsChannel) o;
    return Objects.equals(this.acceptedUser, objsChannel.acceptedUser) &&
        Objects.equals(this.created, objsChannel.created) &&
        Objects.equals(this.creator, objsChannel.creator) &&
        Objects.equals(this.id, objsChannel.id) &&
        Objects.equals(this.isArchived, objsChannel.isArchived) &&
        Objects.equals(this.isChannel, objsChannel.isChannel) &&
        Objects.equals(this.isFrozen, objsChannel.isFrozen) &&
        Objects.equals(this.isGeneral, objsChannel.isGeneral) &&
        Objects.equals(this.isMember, objsChannel.isMember) &&
        Objects.equals(this.isMoved, objsChannel.isMoved) &&
        Objects.equals(this.isMpim, objsChannel.isMpim) &&
        Objects.equals(this.isNonThreadable, objsChannel.isNonThreadable) &&
        Objects.equals(this.isOrgShared, objsChannel.isOrgShared) &&
        Objects.equals(this.isPendingExtShared, objsChannel.isPendingExtShared) &&
        Objects.equals(this.isPrivate, objsChannel.isPrivate) &&
        Objects.equals(this.isReadOnly, objsChannel.isReadOnly) &&
        Objects.equals(this.isShared, objsChannel.isShared) &&
        Objects.equals(this.isThreadOnly, objsChannel.isThreadOnly) &&
        Objects.equals(this.lastRead, objsChannel.lastRead) &&
        Objects.equals(this.latest, objsChannel.latest) &&
        Objects.equals(this.members, objsChannel.members) &&
        Objects.equals(this.name, objsChannel.name) &&
        Objects.equals(this.nameNormalized, objsChannel.nameNormalized) &&
        Objects.equals(this.numMembers, objsChannel.numMembers) &&
        Objects.equals(this.pendingShared, objsChannel.pendingShared) &&
        Objects.equals(this.previousNames, objsChannel.previousNames) &&
        Objects.equals(this.priority, objsChannel.priority) &&
        Objects.equals(this.purpose, objsChannel.purpose) &&
        Objects.equals(this.topic, objsChannel.topic) &&
        Objects.equals(this.unlinked, objsChannel.unlinked) &&
        Objects.equals(this.unreadCount, objsChannel.unreadCount) &&
        Objects.equals(this.unreadCountDisplay, objsChannel.unreadCountDisplay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptedUser, created, creator, id, isArchived, isChannel, isFrozen, isGeneral, isMember, isMoved, isMpim, isNonThreadable, isOrgShared, isPendingExtShared, isPrivate, isReadOnly, isShared, isThreadOnly, lastRead, latest, members, name, nameNormalized, numMembers, pendingShared, previousNames, priority, purpose, topic, unlinked, unreadCount, unreadCountDisplay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjsChannel {\n");
    
    sb.append("    acceptedUser: ").append(toIndentedString(acceptedUser)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isArchived: ").append(toIndentedString(isArchived)).append("\n");
    sb.append("    isChannel: ").append(toIndentedString(isChannel)).append("\n");
    sb.append("    isFrozen: ").append(toIndentedString(isFrozen)).append("\n");
    sb.append("    isGeneral: ").append(toIndentedString(isGeneral)).append("\n");
    sb.append("    isMember: ").append(toIndentedString(isMember)).append("\n");
    sb.append("    isMoved: ").append(toIndentedString(isMoved)).append("\n");
    sb.append("    isMpim: ").append(toIndentedString(isMpim)).append("\n");
    sb.append("    isNonThreadable: ").append(toIndentedString(isNonThreadable)).append("\n");
    sb.append("    isOrgShared: ").append(toIndentedString(isOrgShared)).append("\n");
    sb.append("    isPendingExtShared: ").append(toIndentedString(isPendingExtShared)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    isReadOnly: ").append(toIndentedString(isReadOnly)).append("\n");
    sb.append("    isShared: ").append(toIndentedString(isShared)).append("\n");
    sb.append("    isThreadOnly: ").append(toIndentedString(isThreadOnly)).append("\n");
    sb.append("    lastRead: ").append(toIndentedString(lastRead)).append("\n");
    sb.append("    latest: ").append(toIndentedString(latest)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameNormalized: ").append(toIndentedString(nameNormalized)).append("\n");
    sb.append("    numMembers: ").append(toIndentedString(numMembers)).append("\n");
    sb.append("    pendingShared: ").append(toIndentedString(pendingShared)).append("\n");
    sb.append("    previousNames: ").append(toIndentedString(previousNames)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    unlinked: ").append(toIndentedString(unlinked)).append("\n");
    sb.append("    unreadCount: ").append(toIndentedString(unreadCount)).append("\n");
    sb.append("    unreadCountDisplay: ").append(toIndentedString(unreadCountDisplay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
