/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ObjsTeamIcon
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ObjsTeamIcon {
  @JsonProperty("image_102")
  private String image102 = null;

  @JsonProperty("image_132")
  private String image132 = null;

  @JsonProperty("image_230")
  private String image230 = null;

  @JsonProperty("image_34")
  private String image34 = null;

  @JsonProperty("image_44")
  private String image44 = null;

  @JsonProperty("image_68")
  private String image68 = null;

  @JsonProperty("image_88")
  private String image88 = null;

  @JsonProperty("image_default")
  private Boolean imageDefault = null;

  public ObjsTeamIcon image102(String image102) {
    this.image102 = image102;
    return this;
  }

   /**
   * Get image102
   * @return image102
  **/
  public String getImage102() {
    return image102;
  }

  public void setImage102(String image102) {
    this.image102 = image102;
  }

  public ObjsTeamIcon image132(String image132) {
    this.image132 = image132;
    return this;
  }

   /**
   * Get image132
   * @return image132
  **/
  public String getImage132() {
    return image132;
  }

  public void setImage132(String image132) {
    this.image132 = image132;
  }

  public ObjsTeamIcon image230(String image230) {
    this.image230 = image230;
    return this;
  }

   /**
   * Get image230
   * @return image230
  **/
  public String getImage230() {
    return image230;
  }

  public void setImage230(String image230) {
    this.image230 = image230;
  }

  public ObjsTeamIcon image34(String image34) {
    this.image34 = image34;
    return this;
  }

   /**
   * Get image34
   * @return image34
  **/
  public String getImage34() {
    return image34;
  }

  public void setImage34(String image34) {
    this.image34 = image34;
  }

  public ObjsTeamIcon image44(String image44) {
    this.image44 = image44;
    return this;
  }

   /**
   * Get image44
   * @return image44
  **/
  public String getImage44() {
    return image44;
  }

  public void setImage44(String image44) {
    this.image44 = image44;
  }

  public ObjsTeamIcon image68(String image68) {
    this.image68 = image68;
    return this;
  }

   /**
   * Get image68
   * @return image68
  **/
  public String getImage68() {
    return image68;
  }

  public void setImage68(String image68) {
    this.image68 = image68;
  }

  public ObjsTeamIcon image88(String image88) {
    this.image88 = image88;
    return this;
  }

   /**
   * Get image88
   * @return image88
  **/
  public String getImage88() {
    return image88;
  }

  public void setImage88(String image88) {
    this.image88 = image88;
  }

  public ObjsTeamIcon imageDefault(Boolean imageDefault) {
    this.imageDefault = imageDefault;
    return this;
  }

   /**
   * Get imageDefault
   * @return imageDefault
  **/
  public Boolean isImageDefault() {
    return imageDefault;
  }

  public void setImageDefault(Boolean imageDefault) {
    this.imageDefault = imageDefault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjsTeamIcon objsTeamIcon = (ObjsTeamIcon) o;
    return Objects.equals(this.image102, objsTeamIcon.image102) &&
        Objects.equals(this.image132, objsTeamIcon.image132) &&
        Objects.equals(this.image230, objsTeamIcon.image230) &&
        Objects.equals(this.image34, objsTeamIcon.image34) &&
        Objects.equals(this.image44, objsTeamIcon.image44) &&
        Objects.equals(this.image68, objsTeamIcon.image68) &&
        Objects.equals(this.image88, objsTeamIcon.image88) &&
        Objects.equals(this.imageDefault, objsTeamIcon.imageDefault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(image102, image132, image230, image34, image44, image68, image88, imageDefault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjsTeamIcon {\n");
    
    sb.append("    image102: ").append(toIndentedString(image102)).append("\n");
    sb.append("    image132: ").append(toIndentedString(image132)).append("\n");
    sb.append("    image230: ").append(toIndentedString(image230)).append("\n");
    sb.append("    image34: ").append(toIndentedString(image34)).append("\n");
    sb.append("    image44: ").append(toIndentedString(image44)).append("\n");
    sb.append("    image68: ").append(toIndentedString(image68)).append("\n");
    sb.append("    image88: ").append(toIndentedString(image88)).append("\n");
    sb.append("    imageDefault: ").append(toIndentedString(imageDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
