/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
/**
 * ObjsFile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ObjsFile {
  @JsonProperty("channels")
  private List<String> channels = null;

  @JsonProperty("comments_count")
  private Integer commentsCount = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("date_delete")
  private Integer dateDelete = null;

  @JsonProperty("display_as_bot")
  private Boolean displayAsBot = null;

  @JsonProperty("editable")
  private Boolean editable = null;

  @JsonProperty("editor")
  private String editor = null;

  @JsonProperty("external_id")
  private String externalId = null;

  @JsonProperty("external_type")
  private String externalType = null;

  @JsonProperty("external_url")
  private String externalUrl = null;

  @JsonProperty("filetype")
  private String filetype = null;

  @JsonProperty("groups")
  private List<String> groups = null;

  @JsonProperty("has_rich_preview")
  private Boolean hasRichPreview = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("image_exif_rotation")
  private Integer imageExifRotation = null;

  @JsonProperty("ims")
  private List<String> ims = null;

  @JsonProperty("is_external")
  private Boolean isExternal = null;

  @JsonProperty("is_public")
  private Boolean isPublic = null;

  @JsonProperty("is_starred")
  private Boolean isStarred = null;

  @JsonProperty("is_tombstoned")
  private Boolean isTombstoned = null;

  @JsonProperty("last_editor")
  private String lastEditor = null;

  @JsonProperty("mimetype")
  private String mimetype = null;

  @JsonProperty("mode")
  private String mode = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("non_owner_editable")
  private Boolean nonOwnerEditable = null;

  @JsonProperty("num_stars")
  private Integer numStars = null;

  @JsonProperty("original_h")
  private Integer originalH = null;

  @JsonProperty("original_w")
  private Integer originalW = null;

  @JsonProperty("permalink")
  private String permalink = null;

  @JsonProperty("permalink_public")
  private String permalinkPublic = null;

  @JsonProperty("pinned_info")
  private Object pinnedInfo = null;

  @JsonProperty("pinned_to")
  private List<String> pinnedTo = null;

  @JsonProperty("pretty_type")
  private String prettyType = null;

  @JsonProperty("preview")
  private String preview = null;

  @JsonProperty("public_url_shared")
  private Boolean publicUrlShared = null;

  @JsonProperty("reactions")
  private List<Map> reactions = null;

  @JsonProperty("shares")
  private Object shares = null;

  @JsonProperty("size")
  private Integer size = null;

  @JsonProperty("source_team")
  private String sourceTeam = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("thumb_1024")
  private String thumb1024 = null;

  @JsonProperty("thumb_1024_h")
  private Integer thumb1024H = null;

  @JsonProperty("thumb_1024_w")
  private Integer thumb1024W = null;

  @JsonProperty("thumb_160")
  private String thumb160 = null;

  @JsonProperty("thumb_360")
  private String thumb360 = null;

  @JsonProperty("thumb_360_h")
  private Integer thumb360H = null;

  @JsonProperty("thumb_360_w")
  private Integer thumb360W = null;

  @JsonProperty("thumb_480")
  private String thumb480 = null;

  @JsonProperty("thumb_480_h")
  private Integer thumb480H = null;

  @JsonProperty("thumb_480_w")
  private Integer thumb480W = null;

  @JsonProperty("thumb_64")
  private String thumb64 = null;

  @JsonProperty("thumb_720")
  private String thumb720 = null;

  @JsonProperty("thumb_720_h")
  private Integer thumb720H = null;

  @JsonProperty("thumb_720_w")
  private Integer thumb720W = null;

  @JsonProperty("thumb_80")
  private String thumb80 = null;

  @JsonProperty("thumb_800")
  private String thumb800 = null;

  @JsonProperty("thumb_800_h")
  private Integer thumb800H = null;

  @JsonProperty("thumb_800_w")
  private Integer thumb800W = null;

  @JsonProperty("thumb_960")
  private String thumb960 = null;

  @JsonProperty("thumb_960_h")
  private Integer thumb960H = null;

  @JsonProperty("thumb_960_w")
  private Integer thumb960W = null;

  @JsonProperty("thumb_tiny")
  private String thumbTiny = null;

  @JsonProperty("timestamp")
  private Integer timestamp = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("updated")
  private Integer updated = null;

  @JsonProperty("url_private")
  private String urlPrivate = null;

  @JsonProperty("url_private_download")
  private String urlPrivateDownload = null;

  @JsonProperty("user")
  private String user = null;

  @JsonProperty("user_team")
  private String userTeam = null;

  @JsonProperty("username")
  private String username = null;

  public ObjsFile channels(List<String> channels) {
    this.channels = channels;
    return this;
  }

  public ObjsFile addChannelsItem(String channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<>();
    }
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * Get channels
   * @return channels
  **/
  public List<String> getChannels() {
    return channels;
  }

  public void setChannels(List<String> channels) {
    this.channels = channels;
  }

  public ObjsFile commentsCount(Integer commentsCount) {
    this.commentsCount = commentsCount;
    return this;
  }

   /**
   * Get commentsCount
   * @return commentsCount
  **/
  public Integer getCommentsCount() {
    return commentsCount;
  }

  public void setCommentsCount(Integer commentsCount) {
    this.commentsCount = commentsCount;
  }

  public ObjsFile created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public ObjsFile dateDelete(Integer dateDelete) {
    this.dateDelete = dateDelete;
    return this;
  }

   /**
   * Get dateDelete
   * @return dateDelete
  **/
  public Integer getDateDelete() {
    return dateDelete;
  }

  public void setDateDelete(Integer dateDelete) {
    this.dateDelete = dateDelete;
  }

  public ObjsFile displayAsBot(Boolean displayAsBot) {
    this.displayAsBot = displayAsBot;
    return this;
  }

   /**
   * Get displayAsBot
   * @return displayAsBot
  **/
  public Boolean isDisplayAsBot() {
    return displayAsBot;
  }

  public void setDisplayAsBot(Boolean displayAsBot) {
    this.displayAsBot = displayAsBot;
  }

  public ObjsFile editable(Boolean editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Get editable
   * @return editable
  **/
  public Boolean isEditable() {
    return editable;
  }

  public void setEditable(Boolean editable) {
    this.editable = editable;
  }

  public ObjsFile editor(String editor) {
    this.editor = editor;
    return this;
  }

   /**
   * Get editor
   * @return editor
  **/
  public String getEditor() {
    return editor;
  }

  public void setEditor(String editor) {
    this.editor = editor;
  }

  public ObjsFile externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ObjsFile externalType(String externalType) {
    this.externalType = externalType;
    return this;
  }

   /**
   * Get externalType
   * @return externalType
  **/
  public String getExternalType() {
    return externalType;
  }

  public void setExternalType(String externalType) {
    this.externalType = externalType;
  }

  public ObjsFile externalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
    return this;
  }

   /**
   * Get externalUrl
   * @return externalUrl
  **/
  public String getExternalUrl() {
    return externalUrl;
  }

  public void setExternalUrl(String externalUrl) {
    this.externalUrl = externalUrl;
  }

  public ObjsFile filetype(String filetype) {
    this.filetype = filetype;
    return this;
  }

   /**
   * Get filetype
   * @return filetype
  **/
  public String getFiletype() {
    return filetype;
  }

  public void setFiletype(String filetype) {
    this.filetype = filetype;
  }

  public ObjsFile groups(List<String> groups) {
    this.groups = groups;
    return this;
  }

  public ObjsFile addGroupsItem(String groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  public List<String> getGroups() {
    return groups;
  }

  public void setGroups(List<String> groups) {
    this.groups = groups;
  }

  public ObjsFile hasRichPreview(Boolean hasRichPreview) {
    this.hasRichPreview = hasRichPreview;
    return this;
  }

   /**
   * Get hasRichPreview
   * @return hasRichPreview
  **/
  public Boolean isHasRichPreview() {
    return hasRichPreview;
  }

  public void setHasRichPreview(Boolean hasRichPreview) {
    this.hasRichPreview = hasRichPreview;
  }

  public ObjsFile id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ObjsFile imageExifRotation(Integer imageExifRotation) {
    this.imageExifRotation = imageExifRotation;
    return this;
  }

   /**
   * Get imageExifRotation
   * @return imageExifRotation
  **/
  public Integer getImageExifRotation() {
    return imageExifRotation;
  }

  public void setImageExifRotation(Integer imageExifRotation) {
    this.imageExifRotation = imageExifRotation;
  }

  public ObjsFile ims(List<String> ims) {
    this.ims = ims;
    return this;
  }

  public ObjsFile addImsItem(String imsItem) {
    if (this.ims == null) {
      this.ims = new ArrayList<>();
    }
    this.ims.add(imsItem);
    return this;
  }

   /**
   * Get ims
   * @return ims
  **/
  public List<String> getIms() {
    return ims;
  }

  public void setIms(List<String> ims) {
    this.ims = ims;
  }

  public ObjsFile isExternal(Boolean isExternal) {
    this.isExternal = isExternal;
    return this;
  }

   /**
   * Get isExternal
   * @return isExternal
  **/
  public Boolean isIsExternal() {
    return isExternal;
  }

  public void setIsExternal(Boolean isExternal) {
    this.isExternal = isExternal;
  }

  public ObjsFile isPublic(Boolean isPublic) {
    this.isPublic = isPublic;
    return this;
  }

   /**
   * Get isPublic
   * @return isPublic
  **/
  public Boolean isIsPublic() {
    return isPublic;
  }

  public void setIsPublic(Boolean isPublic) {
    this.isPublic = isPublic;
  }

  public ObjsFile isStarred(Boolean isStarred) {
    this.isStarred = isStarred;
    return this;
  }

   /**
   * Get isStarred
   * @return isStarred
  **/
  public Boolean isIsStarred() {
    return isStarred;
  }

  public void setIsStarred(Boolean isStarred) {
    this.isStarred = isStarred;
  }

  public ObjsFile isTombstoned(Boolean isTombstoned) {
    this.isTombstoned = isTombstoned;
    return this;
  }

   /**
   * Get isTombstoned
   * @return isTombstoned
  **/
  public Boolean isIsTombstoned() {
    return isTombstoned;
  }

  public void setIsTombstoned(Boolean isTombstoned) {
    this.isTombstoned = isTombstoned;
  }

  public ObjsFile lastEditor(String lastEditor) {
    this.lastEditor = lastEditor;
    return this;
  }

   /**
   * Get lastEditor
   * @return lastEditor
  **/
  public String getLastEditor() {
    return lastEditor;
  }

  public void setLastEditor(String lastEditor) {
    this.lastEditor = lastEditor;
  }

  public ObjsFile mimetype(String mimetype) {
    this.mimetype = mimetype;
    return this;
  }

   /**
   * Get mimetype
   * @return mimetype
  **/
  public String getMimetype() {
    return mimetype;
  }

  public void setMimetype(String mimetype) {
    this.mimetype = mimetype;
  }

  public ObjsFile mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public ObjsFile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObjsFile nonOwnerEditable(Boolean nonOwnerEditable) {
    this.nonOwnerEditable = nonOwnerEditable;
    return this;
  }

   /**
   * Get nonOwnerEditable
   * @return nonOwnerEditable
  **/
  public Boolean isNonOwnerEditable() {
    return nonOwnerEditable;
  }

  public void setNonOwnerEditable(Boolean nonOwnerEditable) {
    this.nonOwnerEditable = nonOwnerEditable;
  }

  public ObjsFile numStars(Integer numStars) {
    this.numStars = numStars;
    return this;
  }

   /**
   * Get numStars
   * @return numStars
  **/
  public Integer getNumStars() {
    return numStars;
  }

  public void setNumStars(Integer numStars) {
    this.numStars = numStars;
  }

  public ObjsFile originalH(Integer originalH) {
    this.originalH = originalH;
    return this;
  }

   /**
   * Get originalH
   * @return originalH
  **/
  public Integer getOriginalH() {
    return originalH;
  }

  public void setOriginalH(Integer originalH) {
    this.originalH = originalH;
  }

  public ObjsFile originalW(Integer originalW) {
    this.originalW = originalW;
    return this;
  }

   /**
   * Get originalW
   * @return originalW
  **/
  public Integer getOriginalW() {
    return originalW;
  }

  public void setOriginalW(Integer originalW) {
    this.originalW = originalW;
  }

  public ObjsFile permalink(String permalink) {
    this.permalink = permalink;
    return this;
  }

   /**
   * Get permalink
   * @return permalink
  **/
  public String getPermalink() {
    return permalink;
  }

  public void setPermalink(String permalink) {
    this.permalink = permalink;
  }

  public ObjsFile permalinkPublic(String permalinkPublic) {
    this.permalinkPublic = permalinkPublic;
    return this;
  }

   /**
   * Get permalinkPublic
   * @return permalinkPublic
  **/
  public String getPermalinkPublic() {
    return permalinkPublic;
  }

  public void setPermalinkPublic(String permalinkPublic) {
    this.permalinkPublic = permalinkPublic;
  }

  public ObjsFile pinnedInfo(Object pinnedInfo) {
    this.pinnedInfo = pinnedInfo;
    return this;
  }

   /**
   * Get pinnedInfo
   * @return pinnedInfo
  **/
  public Object getPinnedInfo() {
    return pinnedInfo;
  }

  public void setPinnedInfo(Object pinnedInfo) {
    this.pinnedInfo = pinnedInfo;
  }

  public ObjsFile pinnedTo(List<String> pinnedTo) {
    this.pinnedTo = pinnedTo;
    return this;
  }

  public ObjsFile addPinnedToItem(String pinnedToItem) {
    if (this.pinnedTo == null) {
      this.pinnedTo = new ArrayList<>();
    }
    this.pinnedTo.add(pinnedToItem);
    return this;
  }

   /**
   * Get pinnedTo
   * @return pinnedTo
  **/
  public List<String> getPinnedTo() {
    return pinnedTo;
  }

  public void setPinnedTo(List<String> pinnedTo) {
    this.pinnedTo = pinnedTo;
  }

  public ObjsFile prettyType(String prettyType) {
    this.prettyType = prettyType;
    return this;
  }

   /**
   * Get prettyType
   * @return prettyType
  **/
  public String getPrettyType() {
    return prettyType;
  }

  public void setPrettyType(String prettyType) {
    this.prettyType = prettyType;
  }

  public ObjsFile preview(String preview) {
    this.preview = preview;
    return this;
  }

   /**
   * Get preview
   * @return preview
  **/
  public String getPreview() {
    return preview;
  }

  public void setPreview(String preview) {
    this.preview = preview;
  }

  public ObjsFile publicUrlShared(Boolean publicUrlShared) {
    this.publicUrlShared = publicUrlShared;
    return this;
  }

   /**
   * Get publicUrlShared
   * @return publicUrlShared
  **/
  public Boolean isPublicUrlShared() {
    return publicUrlShared;
  }

  public void setPublicUrlShared(Boolean publicUrlShared) {
    this.publicUrlShared = publicUrlShared;
  }

  public ObjsFile reactions(List<Map> reactions) {
    this.reactions = reactions;
    return this;
  }

  public ObjsFile addReactionsItem(Map reactionsItem) {
    if (this.reactions == null) {
      this.reactions = new ArrayList<>();
    }
    this.reactions.add(reactionsItem);
    return this;
  }

   /**
   * Get reactions
   * @return reactions
  **/
  public List<Map> getReactions() {
    return reactions;
  }

  public void setReactions(List<Map> reactions) {
    this.reactions = reactions;
  }

  public ObjsFile shares(Object shares) {
    this.shares = shares;
    return this;
  }

   /**
   * Get shares
   * @return shares
  **/
  public Object getShares() {
    return shares;
  }

  public void setShares(Object shares) {
    this.shares = shares;
  }

  public ObjsFile size(Integer size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  public Integer getSize() {
    return size;
  }

  public void setSize(Integer size) {
    this.size = size;
  }

  public ObjsFile sourceTeam(String sourceTeam) {
    this.sourceTeam = sourceTeam;
    return this;
  }

   /**
   * Get sourceTeam
   * @return sourceTeam
  **/
  public String getSourceTeam() {
    return sourceTeam;
  }

  public void setSourceTeam(String sourceTeam) {
    this.sourceTeam = sourceTeam;
  }

  public ObjsFile state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ObjsFile thumb1024(String thumb1024) {
    this.thumb1024 = thumb1024;
    return this;
  }

   /**
   * Get thumb1024
   * @return thumb1024
  **/
  public String getThumb1024() {
    return thumb1024;
  }

  public void setThumb1024(String thumb1024) {
    this.thumb1024 = thumb1024;
  }

  public ObjsFile thumb1024H(Integer thumb1024H) {
    this.thumb1024H = thumb1024H;
    return this;
  }

   /**
   * Get thumb1024H
   * @return thumb1024H
  **/
  public Integer getThumb1024H() {
    return thumb1024H;
  }

  public void setThumb1024H(Integer thumb1024H) {
    this.thumb1024H = thumb1024H;
  }

  public ObjsFile thumb1024W(Integer thumb1024W) {
    this.thumb1024W = thumb1024W;
    return this;
  }

   /**
   * Get thumb1024W
   * @return thumb1024W
  **/
  public Integer getThumb1024W() {
    return thumb1024W;
  }

  public void setThumb1024W(Integer thumb1024W) {
    this.thumb1024W = thumb1024W;
  }

  public ObjsFile thumb160(String thumb160) {
    this.thumb160 = thumb160;
    return this;
  }

   /**
   * Get thumb160
   * @return thumb160
  **/
  public String getThumb160() {
    return thumb160;
  }

  public void setThumb160(String thumb160) {
    this.thumb160 = thumb160;
  }

  public ObjsFile thumb360(String thumb360) {
    this.thumb360 = thumb360;
    return this;
  }

   /**
   * Get thumb360
   * @return thumb360
  **/
  public String getThumb360() {
    return thumb360;
  }

  public void setThumb360(String thumb360) {
    this.thumb360 = thumb360;
  }

  public ObjsFile thumb360H(Integer thumb360H) {
    this.thumb360H = thumb360H;
    return this;
  }

   /**
   * Get thumb360H
   * @return thumb360H
  **/
  public Integer getThumb360H() {
    return thumb360H;
  }

  public void setThumb360H(Integer thumb360H) {
    this.thumb360H = thumb360H;
  }

  public ObjsFile thumb360W(Integer thumb360W) {
    this.thumb360W = thumb360W;
    return this;
  }

   /**
   * Get thumb360W
   * @return thumb360W
  **/
  public Integer getThumb360W() {
    return thumb360W;
  }

  public void setThumb360W(Integer thumb360W) {
    this.thumb360W = thumb360W;
  }

  public ObjsFile thumb480(String thumb480) {
    this.thumb480 = thumb480;
    return this;
  }

   /**
   * Get thumb480
   * @return thumb480
  **/
  public String getThumb480() {
    return thumb480;
  }

  public void setThumb480(String thumb480) {
    this.thumb480 = thumb480;
  }

  public ObjsFile thumb480H(Integer thumb480H) {
    this.thumb480H = thumb480H;
    return this;
  }

   /**
   * Get thumb480H
   * @return thumb480H
  **/
  public Integer getThumb480H() {
    return thumb480H;
  }

  public void setThumb480H(Integer thumb480H) {
    this.thumb480H = thumb480H;
  }

  public ObjsFile thumb480W(Integer thumb480W) {
    this.thumb480W = thumb480W;
    return this;
  }

   /**
   * Get thumb480W
   * @return thumb480W
  **/
  public Integer getThumb480W() {
    return thumb480W;
  }

  public void setThumb480W(Integer thumb480W) {
    this.thumb480W = thumb480W;
  }

  public ObjsFile thumb64(String thumb64) {
    this.thumb64 = thumb64;
    return this;
  }

   /**
   * Get thumb64
   * @return thumb64
  **/
  public String getThumb64() {
    return thumb64;
  }

  public void setThumb64(String thumb64) {
    this.thumb64 = thumb64;
  }

  public ObjsFile thumb720(String thumb720) {
    this.thumb720 = thumb720;
    return this;
  }

   /**
   * Get thumb720
   * @return thumb720
  **/
  public String getThumb720() {
    return thumb720;
  }

  public void setThumb720(String thumb720) {
    this.thumb720 = thumb720;
  }

  public ObjsFile thumb720H(Integer thumb720H) {
    this.thumb720H = thumb720H;
    return this;
  }

   /**
   * Get thumb720H
   * @return thumb720H
  **/
  public Integer getThumb720H() {
    return thumb720H;
  }

  public void setThumb720H(Integer thumb720H) {
    this.thumb720H = thumb720H;
  }

  public ObjsFile thumb720W(Integer thumb720W) {
    this.thumb720W = thumb720W;
    return this;
  }

   /**
   * Get thumb720W
   * @return thumb720W
  **/
  public Integer getThumb720W() {
    return thumb720W;
  }

  public void setThumb720W(Integer thumb720W) {
    this.thumb720W = thumb720W;
  }

  public ObjsFile thumb80(String thumb80) {
    this.thumb80 = thumb80;
    return this;
  }

   /**
   * Get thumb80
   * @return thumb80
  **/
  public String getThumb80() {
    return thumb80;
  }

  public void setThumb80(String thumb80) {
    this.thumb80 = thumb80;
  }

  public ObjsFile thumb800(String thumb800) {
    this.thumb800 = thumb800;
    return this;
  }

   /**
   * Get thumb800
   * @return thumb800
  **/
  public String getThumb800() {
    return thumb800;
  }

  public void setThumb800(String thumb800) {
    this.thumb800 = thumb800;
  }

  public ObjsFile thumb800H(Integer thumb800H) {
    this.thumb800H = thumb800H;
    return this;
  }

   /**
   * Get thumb800H
   * @return thumb800H
  **/
  public Integer getThumb800H() {
    return thumb800H;
  }

  public void setThumb800H(Integer thumb800H) {
    this.thumb800H = thumb800H;
  }

  public ObjsFile thumb800W(Integer thumb800W) {
    this.thumb800W = thumb800W;
    return this;
  }

   /**
   * Get thumb800W
   * @return thumb800W
  **/
  public Integer getThumb800W() {
    return thumb800W;
  }

  public void setThumb800W(Integer thumb800W) {
    this.thumb800W = thumb800W;
  }

  public ObjsFile thumb960(String thumb960) {
    this.thumb960 = thumb960;
    return this;
  }

   /**
   * Get thumb960
   * @return thumb960
  **/
  public String getThumb960() {
    return thumb960;
  }

  public void setThumb960(String thumb960) {
    this.thumb960 = thumb960;
  }

  public ObjsFile thumb960H(Integer thumb960H) {
    this.thumb960H = thumb960H;
    return this;
  }

   /**
   * Get thumb960H
   * @return thumb960H
  **/
  public Integer getThumb960H() {
    return thumb960H;
  }

  public void setThumb960H(Integer thumb960H) {
    this.thumb960H = thumb960H;
  }

  public ObjsFile thumb960W(Integer thumb960W) {
    this.thumb960W = thumb960W;
    return this;
  }

   /**
   * Get thumb960W
   * @return thumb960W
  **/
  public Integer getThumb960W() {
    return thumb960W;
  }

  public void setThumb960W(Integer thumb960W) {
    this.thumb960W = thumb960W;
  }

  public ObjsFile thumbTiny(String thumbTiny) {
    this.thumbTiny = thumbTiny;
    return this;
  }

   /**
   * Get thumbTiny
   * @return thumbTiny
  **/
  public String getThumbTiny() {
    return thumbTiny;
  }

  public void setThumbTiny(String thumbTiny) {
    this.thumbTiny = thumbTiny;
  }

  public ObjsFile timestamp(Integer timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  public Integer getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }

  public ObjsFile title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ObjsFile updated(Integer updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  public Integer getUpdated() {
    return updated;
  }

  public void setUpdated(Integer updated) {
    this.updated = updated;
  }

  public ObjsFile urlPrivate(String urlPrivate) {
    this.urlPrivate = urlPrivate;
    return this;
  }

   /**
   * Get urlPrivate
   * @return urlPrivate
  **/
  public String getUrlPrivate() {
    return urlPrivate;
  }

  public void setUrlPrivate(String urlPrivate) {
    this.urlPrivate = urlPrivate;
  }

  public ObjsFile urlPrivateDownload(String urlPrivateDownload) {
    this.urlPrivateDownload = urlPrivateDownload;
    return this;
  }

   /**
   * Get urlPrivateDownload
   * @return urlPrivateDownload
  **/
  public String getUrlPrivateDownload() {
    return urlPrivateDownload;
  }

  public void setUrlPrivateDownload(String urlPrivateDownload) {
    this.urlPrivateDownload = urlPrivateDownload;
  }

  public ObjsFile user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public ObjsFile userTeam(String userTeam) {
    this.userTeam = userTeam;
    return this;
  }

   /**
   * Get userTeam
   * @return userTeam
  **/
  public String getUserTeam() {
    return userTeam;
  }

  public void setUserTeam(String userTeam) {
    this.userTeam = userTeam;
  }

  public ObjsFile username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjsFile objsFile = (ObjsFile) o;
    return Objects.equals(this.channels, objsFile.channels) &&
        Objects.equals(this.commentsCount, objsFile.commentsCount) &&
        Objects.equals(this.created, objsFile.created) &&
        Objects.equals(this.dateDelete, objsFile.dateDelete) &&
        Objects.equals(this.displayAsBot, objsFile.displayAsBot) &&
        Objects.equals(this.editable, objsFile.editable) &&
        Objects.equals(this.editor, objsFile.editor) &&
        Objects.equals(this.externalId, objsFile.externalId) &&
        Objects.equals(this.externalType, objsFile.externalType) &&
        Objects.equals(this.externalUrl, objsFile.externalUrl) &&
        Objects.equals(this.filetype, objsFile.filetype) &&
        Objects.equals(this.groups, objsFile.groups) &&
        Objects.equals(this.hasRichPreview, objsFile.hasRichPreview) &&
        Objects.equals(this.id, objsFile.id) &&
        Objects.equals(this.imageExifRotation, objsFile.imageExifRotation) &&
        Objects.equals(this.ims, objsFile.ims) &&
        Objects.equals(this.isExternal, objsFile.isExternal) &&
        Objects.equals(this.isPublic, objsFile.isPublic) &&
        Objects.equals(this.isStarred, objsFile.isStarred) &&
        Objects.equals(this.isTombstoned, objsFile.isTombstoned) &&
        Objects.equals(this.lastEditor, objsFile.lastEditor) &&
        Objects.equals(this.mimetype, objsFile.mimetype) &&
        Objects.equals(this.mode, objsFile.mode) &&
        Objects.equals(this.name, objsFile.name) &&
        Objects.equals(this.nonOwnerEditable, objsFile.nonOwnerEditable) &&
        Objects.equals(this.numStars, objsFile.numStars) &&
        Objects.equals(this.originalH, objsFile.originalH) &&
        Objects.equals(this.originalW, objsFile.originalW) &&
        Objects.equals(this.permalink, objsFile.permalink) &&
        Objects.equals(this.permalinkPublic, objsFile.permalinkPublic) &&
        Objects.equals(this.pinnedInfo, objsFile.pinnedInfo) &&
        Objects.equals(this.pinnedTo, objsFile.pinnedTo) &&
        Objects.equals(this.prettyType, objsFile.prettyType) &&
        Objects.equals(this.preview, objsFile.preview) &&
        Objects.equals(this.publicUrlShared, objsFile.publicUrlShared) &&
        Objects.equals(this.reactions, objsFile.reactions) &&
        Objects.equals(this.shares, objsFile.shares) &&
        Objects.equals(this.size, objsFile.size) &&
        Objects.equals(this.sourceTeam, objsFile.sourceTeam) &&
        Objects.equals(this.state, objsFile.state) &&
        Objects.equals(this.thumb1024, objsFile.thumb1024) &&
        Objects.equals(this.thumb1024H, objsFile.thumb1024H) &&
        Objects.equals(this.thumb1024W, objsFile.thumb1024W) &&
        Objects.equals(this.thumb160, objsFile.thumb160) &&
        Objects.equals(this.thumb360, objsFile.thumb360) &&
        Objects.equals(this.thumb360H, objsFile.thumb360H) &&
        Objects.equals(this.thumb360W, objsFile.thumb360W) &&
        Objects.equals(this.thumb480, objsFile.thumb480) &&
        Objects.equals(this.thumb480H, objsFile.thumb480H) &&
        Objects.equals(this.thumb480W, objsFile.thumb480W) &&
        Objects.equals(this.thumb64, objsFile.thumb64) &&
        Objects.equals(this.thumb720, objsFile.thumb720) &&
        Objects.equals(this.thumb720H, objsFile.thumb720H) &&
        Objects.equals(this.thumb720W, objsFile.thumb720W) &&
        Objects.equals(this.thumb80, objsFile.thumb80) &&
        Objects.equals(this.thumb800, objsFile.thumb800) &&
        Objects.equals(this.thumb800H, objsFile.thumb800H) &&
        Objects.equals(this.thumb800W, objsFile.thumb800W) &&
        Objects.equals(this.thumb960, objsFile.thumb960) &&
        Objects.equals(this.thumb960H, objsFile.thumb960H) &&
        Objects.equals(this.thumb960W, objsFile.thumb960W) &&
        Objects.equals(this.thumbTiny, objsFile.thumbTiny) &&
        Objects.equals(this.timestamp, objsFile.timestamp) &&
        Objects.equals(this.title, objsFile.title) &&
        Objects.equals(this.updated, objsFile.updated) &&
        Objects.equals(this.urlPrivate, objsFile.urlPrivate) &&
        Objects.equals(this.urlPrivateDownload, objsFile.urlPrivateDownload) &&
        Objects.equals(this.user, objsFile.user) &&
        Objects.equals(this.userTeam, objsFile.userTeam) &&
        Objects.equals(this.username, objsFile.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channels, commentsCount, created, dateDelete, displayAsBot, editable, editor, externalId, externalType, externalUrl, filetype, groups, hasRichPreview, id, imageExifRotation, ims, isExternal, isPublic, isStarred, isTombstoned, lastEditor, mimetype, mode, name, nonOwnerEditable, numStars, originalH, originalW, permalink, permalinkPublic, pinnedInfo, pinnedTo, prettyType, preview, publicUrlShared, reactions, shares, size, sourceTeam, state, thumb1024, thumb1024H, thumb1024W, thumb160, thumb360, thumb360H, thumb360W, thumb480, thumb480H, thumb480W, thumb64, thumb720, thumb720H, thumb720W, thumb80, thumb800, thumb800H, thumb800W, thumb960, thumb960H, thumb960W, thumbTiny, timestamp, title, updated, urlPrivate, urlPrivateDownload, user, userTeam, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjsFile {\n");
    
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    commentsCount: ").append(toIndentedString(commentsCount)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    dateDelete: ").append(toIndentedString(dateDelete)).append("\n");
    sb.append("    displayAsBot: ").append(toIndentedString(displayAsBot)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    editor: ").append(toIndentedString(editor)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    externalType: ").append(toIndentedString(externalType)).append("\n");
    sb.append("    externalUrl: ").append(toIndentedString(externalUrl)).append("\n");
    sb.append("    filetype: ").append(toIndentedString(filetype)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    hasRichPreview: ").append(toIndentedString(hasRichPreview)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageExifRotation: ").append(toIndentedString(imageExifRotation)).append("\n");
    sb.append("    ims: ").append(toIndentedString(ims)).append("\n");
    sb.append("    isExternal: ").append(toIndentedString(isExternal)).append("\n");
    sb.append("    isPublic: ").append(toIndentedString(isPublic)).append("\n");
    sb.append("    isStarred: ").append(toIndentedString(isStarred)).append("\n");
    sb.append("    isTombstoned: ").append(toIndentedString(isTombstoned)).append("\n");
    sb.append("    lastEditor: ").append(toIndentedString(lastEditor)).append("\n");
    sb.append("    mimetype: ").append(toIndentedString(mimetype)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nonOwnerEditable: ").append(toIndentedString(nonOwnerEditable)).append("\n");
    sb.append("    numStars: ").append(toIndentedString(numStars)).append("\n");
    sb.append("    originalH: ").append(toIndentedString(originalH)).append("\n");
    sb.append("    originalW: ").append(toIndentedString(originalW)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    permalinkPublic: ").append(toIndentedString(permalinkPublic)).append("\n");
    sb.append("    pinnedInfo: ").append(toIndentedString(pinnedInfo)).append("\n");
    sb.append("    pinnedTo: ").append(toIndentedString(pinnedTo)).append("\n");
    sb.append("    prettyType: ").append(toIndentedString(prettyType)).append("\n");
    sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
    sb.append("    publicUrlShared: ").append(toIndentedString(publicUrlShared)).append("\n");
    sb.append("    reactions: ").append(toIndentedString(reactions)).append("\n");
    sb.append("    shares: ").append(toIndentedString(shares)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    sourceTeam: ").append(toIndentedString(sourceTeam)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    thumb1024: ").append(toIndentedString(thumb1024)).append("\n");
    sb.append("    thumb1024H: ").append(toIndentedString(thumb1024H)).append("\n");
    sb.append("    thumb1024W: ").append(toIndentedString(thumb1024W)).append("\n");
    sb.append("    thumb160: ").append(toIndentedString(thumb160)).append("\n");
    sb.append("    thumb360: ").append(toIndentedString(thumb360)).append("\n");
    sb.append("    thumb360H: ").append(toIndentedString(thumb360H)).append("\n");
    sb.append("    thumb360W: ").append(toIndentedString(thumb360W)).append("\n");
    sb.append("    thumb480: ").append(toIndentedString(thumb480)).append("\n");
    sb.append("    thumb480H: ").append(toIndentedString(thumb480H)).append("\n");
    sb.append("    thumb480W: ").append(toIndentedString(thumb480W)).append("\n");
    sb.append("    thumb64: ").append(toIndentedString(thumb64)).append("\n");
    sb.append("    thumb720: ").append(toIndentedString(thumb720)).append("\n");
    sb.append("    thumb720H: ").append(toIndentedString(thumb720H)).append("\n");
    sb.append("    thumb720W: ").append(toIndentedString(thumb720W)).append("\n");
    sb.append("    thumb80: ").append(toIndentedString(thumb80)).append("\n");
    sb.append("    thumb800: ").append(toIndentedString(thumb800)).append("\n");
    sb.append("    thumb800H: ").append(toIndentedString(thumb800H)).append("\n");
    sb.append("    thumb800W: ").append(toIndentedString(thumb800W)).append("\n");
    sb.append("    thumb960: ").append(toIndentedString(thumb960)).append("\n");
    sb.append("    thumb960H: ").append(toIndentedString(thumb960H)).append("\n");
    sb.append("    thumb960W: ").append(toIndentedString(thumb960W)).append("\n");
    sb.append("    thumbTiny: ").append(toIndentedString(thumbTiny)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    urlPrivate: ").append(toIndentedString(urlPrivate)).append("\n");
    sb.append("    urlPrivateDownload: ").append(toIndentedString(urlPrivateDownload)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userTeam: ").append(toIndentedString(userTeam)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
