/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ObjsUserProfileShort
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ObjsUserProfileShort {
  @JsonProperty("avatar_hash")
  private String avatarHash = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("display_name_normalized")
  private String displayNameNormalized = null;

  @JsonProperty("image_72")
  private String image72 = null;

  @JsonProperty("is_restricted")
  private Boolean isRestricted = null;

  @JsonProperty("is_ultra_restricted")
  private Boolean isUltraRestricted = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("real_name")
  private String realName = null;

  @JsonProperty("real_name_normalized")
  private String realNameNormalized = null;

  @JsonProperty("team")
  private String team = null;

  public ObjsUserProfileShort avatarHash(String avatarHash) {
    this.avatarHash = avatarHash;
    return this;
  }

   /**
   * Get avatarHash
   * @return avatarHash
  **/
  public String getAvatarHash() {
    return avatarHash;
  }

  public void setAvatarHash(String avatarHash) {
    this.avatarHash = avatarHash;
  }

  public ObjsUserProfileShort displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ObjsUserProfileShort displayNameNormalized(String displayNameNormalized) {
    this.displayNameNormalized = displayNameNormalized;
    return this;
  }

   /**
   * Get displayNameNormalized
   * @return displayNameNormalized
  **/
  public String getDisplayNameNormalized() {
    return displayNameNormalized;
  }

  public void setDisplayNameNormalized(String displayNameNormalized) {
    this.displayNameNormalized = displayNameNormalized;
  }

  public ObjsUserProfileShort image72(String image72) {
    this.image72 = image72;
    return this;
  }

   /**
   * Get image72
   * @return image72
  **/
  public String getImage72() {
    return image72;
  }

  public void setImage72(String image72) {
    this.image72 = image72;
  }

  public ObjsUserProfileShort isRestricted(Boolean isRestricted) {
    this.isRestricted = isRestricted;
    return this;
  }

   /**
   * Get isRestricted
   * @return isRestricted
  **/
  public Boolean isIsRestricted() {
    return isRestricted;
  }

  public void setIsRestricted(Boolean isRestricted) {
    this.isRestricted = isRestricted;
  }

  public ObjsUserProfileShort isUltraRestricted(Boolean isUltraRestricted) {
    this.isUltraRestricted = isUltraRestricted;
    return this;
  }

   /**
   * Get isUltraRestricted
   * @return isUltraRestricted
  **/
  public Boolean isIsUltraRestricted() {
    return isUltraRestricted;
  }

  public void setIsUltraRestricted(Boolean isUltraRestricted) {
    this.isUltraRestricted = isUltraRestricted;
  }

  public ObjsUserProfileShort name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObjsUserProfileShort realName(String realName) {
    this.realName = realName;
    return this;
  }

   /**
   * Get realName
   * @return realName
  **/
  public String getRealName() {
    return realName;
  }

  public void setRealName(String realName) {
    this.realName = realName;
  }

  public ObjsUserProfileShort realNameNormalized(String realNameNormalized) {
    this.realNameNormalized = realNameNormalized;
    return this;
  }

   /**
   * Get realNameNormalized
   * @return realNameNormalized
  **/
  public String getRealNameNormalized() {
    return realNameNormalized;
  }

  public void setRealNameNormalized(String realNameNormalized) {
    this.realNameNormalized = realNameNormalized;
  }

  public ObjsUserProfileShort team(String team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  public String getTeam() {
    return team;
  }

  public void setTeam(String team) {
    this.team = team;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjsUserProfileShort objsUserProfileShort = (ObjsUserProfileShort) o;
    return Objects.equals(this.avatarHash, objsUserProfileShort.avatarHash) &&
        Objects.equals(this.displayName, objsUserProfileShort.displayName) &&
        Objects.equals(this.displayNameNormalized, objsUserProfileShort.displayNameNormalized) &&
        Objects.equals(this.image72, objsUserProfileShort.image72) &&
        Objects.equals(this.isRestricted, objsUserProfileShort.isRestricted) &&
        Objects.equals(this.isUltraRestricted, objsUserProfileShort.isUltraRestricted) &&
        Objects.equals(this.name, objsUserProfileShort.name) &&
        Objects.equals(this.realName, objsUserProfileShort.realName) &&
        Objects.equals(this.realNameNormalized, objsUserProfileShort.realNameNormalized) &&
        Objects.equals(this.team, objsUserProfileShort.team);
  }

  @Override
  public int hashCode() {
    return Objects.hash(avatarHash, displayName, displayNameNormalized, image72, isRestricted, isUltraRestricted, name, realName, realNameNormalized, team);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjsUserProfileShort {\n");
    
    sb.append("    avatarHash: ").append(toIndentedString(avatarHash)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    displayNameNormalized: ").append(toIndentedString(displayNameNormalized)).append("\n");
    sb.append("    image72: ").append(toIndentedString(image72)).append("\n");
    sb.append("    isRestricted: ").append(toIndentedString(isRestricted)).append("\n");
    sb.append("    isUltraRestricted: ").append(toIndentedString(isUltraRestricted)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    realName: ").append(toIndentedString(realName)).append("\n");
    sb.append("    realNameNormalized: ").append(toIndentedString(realNameNormalized)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
