/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.BotProfileObject;
import com.slack.api.client.FileCommentObject;
import com.slack.api.client.FileObject;
import com.slack.api.client.ObjsMessageUserProfile;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
/**
 * ObjsMessage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ObjsMessage {
  @JsonProperty("attachments")
  private List<Object> attachments = null;

  @JsonProperty("blocks")
  private List<Map<String, Object>> blocks = null;

  @JsonProperty("bot_id")
  private Object botId = null;

  @JsonProperty("bot_profile")
  private BotProfileObject botProfile = null;

  @JsonProperty("client_msg_id")
  private String clientMsgId = null;

  @JsonProperty("comment")
  private FileCommentObject comment = null;

  @JsonProperty("display_as_bot")
  private Boolean displayAsBot = null;

  @JsonProperty("file")
  private FileObject file = null;

  @JsonProperty("files")
  private List<FileObject> files = null;

  @JsonProperty("icons")
  private Object icons = null;

  @JsonProperty("inviter")
  private String inviter = null;

  @JsonProperty("is_delayed_message")
  private Boolean isDelayedMessage = null;

  @JsonProperty("is_intro")
  private Boolean isIntro = null;

  @JsonProperty("is_starred")
  private Boolean isStarred = null;

  @JsonProperty("last_read")
  private String lastRead = null;

  @JsonProperty("latest_reply")
  private String latestReply = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("old_name")
  private String oldName = null;

  @JsonProperty("parent_user_id")
  private String parentUserId = null;

  @JsonProperty("permalink")
  private String permalink = null;

  @JsonProperty("pinned_to")
  private List<String> pinnedTo = null;

  @JsonProperty("purpose")
  private String purpose = null;

  @JsonProperty("reactions")
  private List<Map> reactions = null;

  @JsonProperty("reply_count")
  private Integer replyCount = null;

  @JsonProperty("reply_users")
  private List<String> replyUsers = null;

  @JsonProperty("reply_users_count")
  private Integer replyUsersCount = null;

  @JsonProperty("source_team")
  private String sourceTeam = null;

  @JsonProperty("subscribed")
  private Boolean subscribed = null;

  @JsonProperty("subtype")
  private String subtype = null;

  @JsonProperty("team")
  private String team = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("thread_ts")
  private String threadTs = null;

  @JsonProperty("topic")
  private String topic = null;

  @JsonProperty("ts")
  private String ts = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("unread_count")
  private Integer unreadCount = null;

  @JsonProperty("upload")
  private Boolean upload = null;

  @JsonProperty("user")
  private String user = null;

  @JsonProperty("user_profile")
  private ObjsMessageUserProfile userProfile = null;

  @JsonProperty("user_team")
  private String userTeam = null;

  @JsonProperty("username")
  private String username = null;

  public ObjsMessage attachments(List<Object> attachments) {
    this.attachments = attachments;
    return this;
  }

  public ObjsMessage addAttachmentsItem(Object attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  public List<Object> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<Object> attachments) {
    this.attachments = attachments;
  }

  public ObjsMessage blocks(List<Map<String, Object>> blocks) {
    this.blocks = blocks;
    return this;
  }

  public ObjsMessage addBlocksItem(Map<String, Object> blocksItem) {
    if (this.blocks == null) {
      this.blocks = new ArrayList<>();
    }
    this.blocks.add(blocksItem);
    return this;
  }

   /**
   * This is a very loose definition, in the future, we&#x27;ll populate this with deeper schema in this definition namespace.
   * @return blocks
  **/
  public List<Map<String, Object>> getBlocks() {
    return blocks;
  }

  public void setBlocks(List<Map<String, Object>> blocks) {
    this.blocks = blocks;
  }

  public ObjsMessage botId(Object botId) {
    this.botId = botId;
    return this;
  }

   /**
   * Get botId
   * @return botId
  **/
  public Object getBotId() {
    return botId;
  }

  public void setBotId(Object botId) {
    this.botId = botId;
  }

  public ObjsMessage botProfile(BotProfileObject botProfile) {
    this.botProfile = botProfile;
    return this;
  }

   /**
   * Get botProfile
   * @return botProfile
  **/
  public BotProfileObject getBotProfile() {
    return botProfile;
  }

  public void setBotProfile(BotProfileObject botProfile) {
    this.botProfile = botProfile;
  }

  public ObjsMessage clientMsgId(String clientMsgId) {
    this.clientMsgId = clientMsgId;
    return this;
  }

   /**
   * Get clientMsgId
   * @return clientMsgId
  **/
  public String getClientMsgId() {
    return clientMsgId;
  }

  public void setClientMsgId(String clientMsgId) {
    this.clientMsgId = clientMsgId;
  }

  public ObjsMessage comment(FileCommentObject comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  public FileCommentObject getComment() {
    return comment;
  }

  public void setComment(FileCommentObject comment) {
    this.comment = comment;
  }

  public ObjsMessage displayAsBot(Boolean displayAsBot) {
    this.displayAsBot = displayAsBot;
    return this;
  }

   /**
   * Get displayAsBot
   * @return displayAsBot
  **/
  public Boolean isDisplayAsBot() {
    return displayAsBot;
  }

  public void setDisplayAsBot(Boolean displayAsBot) {
    this.displayAsBot = displayAsBot;
  }

  public ObjsMessage file(FileObject file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  public FileObject getFile() {
    return file;
  }

  public void setFile(FileObject file) {
    this.file = file;
  }

  public ObjsMessage files(List<FileObject> files) {
    this.files = files;
    return this;
  }

  public ObjsMessage addFilesItem(FileObject filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  public List<FileObject> getFiles() {
    return files;
  }

  public void setFiles(List<FileObject> files) {
    this.files = files;
  }

  public ObjsMessage icons(Object icons) {
    this.icons = icons;
    return this;
  }

   /**
   * Get icons
   * @return icons
  **/
  public Object getIcons() {
    return icons;
  }

  public void setIcons(Object icons) {
    this.icons = icons;
  }

  public ObjsMessage inviter(String inviter) {
    this.inviter = inviter;
    return this;
  }

   /**
   * Get inviter
   * @return inviter
  **/
  public String getInviter() {
    return inviter;
  }

  public void setInviter(String inviter) {
    this.inviter = inviter;
  }

  public ObjsMessage isDelayedMessage(Boolean isDelayedMessage) {
    this.isDelayedMessage = isDelayedMessage;
    return this;
  }

   /**
   * Get isDelayedMessage
   * @return isDelayedMessage
  **/
  public Boolean isIsDelayedMessage() {
    return isDelayedMessage;
  }

  public void setIsDelayedMessage(Boolean isDelayedMessage) {
    this.isDelayedMessage = isDelayedMessage;
  }

  public ObjsMessage isIntro(Boolean isIntro) {
    this.isIntro = isIntro;
    return this;
  }

   /**
   * Get isIntro
   * @return isIntro
  **/
  public Boolean isIsIntro() {
    return isIntro;
  }

  public void setIsIntro(Boolean isIntro) {
    this.isIntro = isIntro;
  }

  public ObjsMessage isStarred(Boolean isStarred) {
    this.isStarred = isStarred;
    return this;
  }

   /**
   * Get isStarred
   * @return isStarred
  **/
  public Boolean isIsStarred() {
    return isStarred;
  }

  public void setIsStarred(Boolean isStarred) {
    this.isStarred = isStarred;
  }

  public ObjsMessage lastRead(String lastRead) {
    this.lastRead = lastRead;
    return this;
  }

   /**
   * Get lastRead
   * @return lastRead
  **/
  public String getLastRead() {
    return lastRead;
  }

  public void setLastRead(String lastRead) {
    this.lastRead = lastRead;
  }

  public ObjsMessage latestReply(String latestReply) {
    this.latestReply = latestReply;
    return this;
  }

   /**
   * Get latestReply
   * @return latestReply
  **/
  public String getLatestReply() {
    return latestReply;
  }

  public void setLatestReply(String latestReply) {
    this.latestReply = latestReply;
  }

  public ObjsMessage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ObjsMessage oldName(String oldName) {
    this.oldName = oldName;
    return this;
  }

   /**
   * Get oldName
   * @return oldName
  **/
  public String getOldName() {
    return oldName;
  }

  public void setOldName(String oldName) {
    this.oldName = oldName;
  }

  public ObjsMessage parentUserId(String parentUserId) {
    this.parentUserId = parentUserId;
    return this;
  }

   /**
   * Get parentUserId
   * @return parentUserId
  **/
  public String getParentUserId() {
    return parentUserId;
  }

  public void setParentUserId(String parentUserId) {
    this.parentUserId = parentUserId;
  }

  public ObjsMessage permalink(String permalink) {
    this.permalink = permalink;
    return this;
  }

   /**
   * Get permalink
   * @return permalink
  **/
  public String getPermalink() {
    return permalink;
  }

  public void setPermalink(String permalink) {
    this.permalink = permalink;
  }

  public ObjsMessage pinnedTo(List<String> pinnedTo) {
    this.pinnedTo = pinnedTo;
    return this;
  }

  public ObjsMessage addPinnedToItem(String pinnedToItem) {
    if (this.pinnedTo == null) {
      this.pinnedTo = new ArrayList<>();
    }
    this.pinnedTo.add(pinnedToItem);
    return this;
  }

   /**
   * Get pinnedTo
   * @return pinnedTo
  **/
  public List<String> getPinnedTo() {
    return pinnedTo;
  }

  public void setPinnedTo(List<String> pinnedTo) {
    this.pinnedTo = pinnedTo;
  }

  public ObjsMessage purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

   /**
   * Get purpose
   * @return purpose
  **/
  public String getPurpose() {
    return purpose;
  }

  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public ObjsMessage reactions(List<Map> reactions) {
    this.reactions = reactions;
    return this;
  }

  public ObjsMessage addReactionsItem(Map reactionsItem) {
    if (this.reactions == null) {
      this.reactions = new ArrayList<>();
    }
    this.reactions.add(reactionsItem);
    return this;
  }

   /**
   * Get reactions
   * @return reactions
  **/
  public List<Map> getReactions() {
    return reactions;
  }

  public void setReactions(List<Map> reactions) {
    this.reactions = reactions;
  }

  public ObjsMessage replyCount(Integer replyCount) {
    this.replyCount = replyCount;
    return this;
  }

   /**
   * Get replyCount
   * @return replyCount
  **/
  public Integer getReplyCount() {
    return replyCount;
  }

  public void setReplyCount(Integer replyCount) {
    this.replyCount = replyCount;
  }

  public ObjsMessage replyUsers(List<String> replyUsers) {
    this.replyUsers = replyUsers;
    return this;
  }

  public ObjsMessage addReplyUsersItem(String replyUsersItem) {
    if (this.replyUsers == null) {
      this.replyUsers = new ArrayList<>();
    }
    this.replyUsers.add(replyUsersItem);
    return this;
  }

   /**
   * Get replyUsers
   * @return replyUsers
  **/
  public List<String> getReplyUsers() {
    return replyUsers;
  }

  public void setReplyUsers(List<String> replyUsers) {
    this.replyUsers = replyUsers;
  }

  public ObjsMessage replyUsersCount(Integer replyUsersCount) {
    this.replyUsersCount = replyUsersCount;
    return this;
  }

   /**
   * Get replyUsersCount
   * @return replyUsersCount
  **/
  public Integer getReplyUsersCount() {
    return replyUsersCount;
  }

  public void setReplyUsersCount(Integer replyUsersCount) {
    this.replyUsersCount = replyUsersCount;
  }

  public ObjsMessage sourceTeam(String sourceTeam) {
    this.sourceTeam = sourceTeam;
    return this;
  }

   /**
   * Get sourceTeam
   * @return sourceTeam
  **/
  public String getSourceTeam() {
    return sourceTeam;
  }

  public void setSourceTeam(String sourceTeam) {
    this.sourceTeam = sourceTeam;
  }

  public ObjsMessage subscribed(Boolean subscribed) {
    this.subscribed = subscribed;
    return this;
  }

   /**
   * Get subscribed
   * @return subscribed
  **/
  public Boolean isSubscribed() {
    return subscribed;
  }

  public void setSubscribed(Boolean subscribed) {
    this.subscribed = subscribed;
  }

  public ObjsMessage subtype(String subtype) {
    this.subtype = subtype;
    return this;
  }

   /**
   * Get subtype
   * @return subtype
  **/
  public String getSubtype() {
    return subtype;
  }

  public void setSubtype(String subtype) {
    this.subtype = subtype;
  }

  public ObjsMessage team(String team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  public String getTeam() {
    return team;
  }

  public void setTeam(String team) {
    this.team = team;
  }

  public ObjsMessage text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public ObjsMessage threadTs(String threadTs) {
    this.threadTs = threadTs;
    return this;
  }

   /**
   * Get threadTs
   * @return threadTs
  **/
  public String getThreadTs() {
    return threadTs;
  }

  public void setThreadTs(String threadTs) {
    this.threadTs = threadTs;
  }

  public ObjsMessage topic(String topic) {
    this.topic = topic;
    return this;
  }

   /**
   * Get topic
   * @return topic
  **/
  public String getTopic() {
    return topic;
  }

  public void setTopic(String topic) {
    this.topic = topic;
  }

  public ObjsMessage ts(String ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Get ts
   * @return ts
  **/
  public String getTs() {
    return ts;
  }

  public void setTs(String ts) {
    this.ts = ts;
  }

  public ObjsMessage type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ObjsMessage unreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
    return this;
  }

   /**
   * Get unreadCount
   * @return unreadCount
  **/
  public Integer getUnreadCount() {
    return unreadCount;
  }

  public void setUnreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
  }

  public ObjsMessage upload(Boolean upload) {
    this.upload = upload;
    return this;
  }

   /**
   * Get upload
   * @return upload
  **/
  public Boolean isUpload() {
    return upload;
  }

  public void setUpload(Boolean upload) {
    this.upload = upload;
  }

  public ObjsMessage user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public ObjsMessage userProfile(ObjsMessageUserProfile userProfile) {
    this.userProfile = userProfile;
    return this;
  }

   /**
   * Get userProfile
   * @return userProfile
  **/
  public ObjsMessageUserProfile getUserProfile() {
    return userProfile;
  }

  public void setUserProfile(ObjsMessageUserProfile userProfile) {
    this.userProfile = userProfile;
  }

  public ObjsMessage userTeam(String userTeam) {
    this.userTeam = userTeam;
    return this;
  }

   /**
   * Get userTeam
   * @return userTeam
  **/
  public String getUserTeam() {
    return userTeam;
  }

  public void setUserTeam(String userTeam) {
    this.userTeam = userTeam;
  }

  public ObjsMessage username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjsMessage objsMessage = (ObjsMessage) o;
    return Objects.equals(this.attachments, objsMessage.attachments) &&
        Objects.equals(this.blocks, objsMessage.blocks) &&
        Objects.equals(this.botId, objsMessage.botId) &&
        Objects.equals(this.botProfile, objsMessage.botProfile) &&
        Objects.equals(this.clientMsgId, objsMessage.clientMsgId) &&
        Objects.equals(this.comment, objsMessage.comment) &&
        Objects.equals(this.displayAsBot, objsMessage.displayAsBot) &&
        Objects.equals(this.file, objsMessage.file) &&
        Objects.equals(this.files, objsMessage.files) &&
        Objects.equals(this.icons, objsMessage.icons) &&
        Objects.equals(this.inviter, objsMessage.inviter) &&
        Objects.equals(this.isDelayedMessage, objsMessage.isDelayedMessage) &&
        Objects.equals(this.isIntro, objsMessage.isIntro) &&
        Objects.equals(this.isStarred, objsMessage.isStarred) &&
        Objects.equals(this.lastRead, objsMessage.lastRead) &&
        Objects.equals(this.latestReply, objsMessage.latestReply) &&
        Objects.equals(this.name, objsMessage.name) &&
        Objects.equals(this.oldName, objsMessage.oldName) &&
        Objects.equals(this.parentUserId, objsMessage.parentUserId) &&
        Objects.equals(this.permalink, objsMessage.permalink) &&
        Objects.equals(this.pinnedTo, objsMessage.pinnedTo) &&
        Objects.equals(this.purpose, objsMessage.purpose) &&
        Objects.equals(this.reactions, objsMessage.reactions) &&
        Objects.equals(this.replyCount, objsMessage.replyCount) &&
        Objects.equals(this.replyUsers, objsMessage.replyUsers) &&
        Objects.equals(this.replyUsersCount, objsMessage.replyUsersCount) &&
        Objects.equals(this.sourceTeam, objsMessage.sourceTeam) &&
        Objects.equals(this.subscribed, objsMessage.subscribed) &&
        Objects.equals(this.subtype, objsMessage.subtype) &&
        Objects.equals(this.team, objsMessage.team) &&
        Objects.equals(this.text, objsMessage.text) &&
        Objects.equals(this.threadTs, objsMessage.threadTs) &&
        Objects.equals(this.topic, objsMessage.topic) &&
        Objects.equals(this.ts, objsMessage.ts) &&
        Objects.equals(this.type, objsMessage.type) &&
        Objects.equals(this.unreadCount, objsMessage.unreadCount) &&
        Objects.equals(this.upload, objsMessage.upload) &&
        Objects.equals(this.user, objsMessage.user) &&
        Objects.equals(this.userProfile, objsMessage.userProfile) &&
        Objects.equals(this.userTeam, objsMessage.userTeam) &&
        Objects.equals(this.username, objsMessage.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachments, blocks, botId, botProfile, clientMsgId, comment, displayAsBot, file, files, icons, inviter, isDelayedMessage, isIntro, isStarred, lastRead, latestReply, name, oldName, parentUserId, permalink, pinnedTo, purpose, reactions, replyCount, replyUsers, replyUsersCount, sourceTeam, subscribed, subtype, team, text, threadTs, topic, ts, type, unreadCount, upload, user, userProfile, userTeam, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjsMessage {\n");
    
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    blocks: ").append(toIndentedString(blocks)).append("\n");
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    botProfile: ").append(toIndentedString(botProfile)).append("\n");
    sb.append("    clientMsgId: ").append(toIndentedString(clientMsgId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    displayAsBot: ").append(toIndentedString(displayAsBot)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    icons: ").append(toIndentedString(icons)).append("\n");
    sb.append("    inviter: ").append(toIndentedString(inviter)).append("\n");
    sb.append("    isDelayedMessage: ").append(toIndentedString(isDelayedMessage)).append("\n");
    sb.append("    isIntro: ").append(toIndentedString(isIntro)).append("\n");
    sb.append("    isStarred: ").append(toIndentedString(isStarred)).append("\n");
    sb.append("    lastRead: ").append(toIndentedString(lastRead)).append("\n");
    sb.append("    latestReply: ").append(toIndentedString(latestReply)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oldName: ").append(toIndentedString(oldName)).append("\n");
    sb.append("    parentUserId: ").append(toIndentedString(parentUserId)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    pinnedTo: ").append(toIndentedString(pinnedTo)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    reactions: ").append(toIndentedString(reactions)).append("\n");
    sb.append("    replyCount: ").append(toIndentedString(replyCount)).append("\n");
    sb.append("    replyUsers: ").append(toIndentedString(replyUsers)).append("\n");
    sb.append("    replyUsersCount: ").append(toIndentedString(replyUsersCount)).append("\n");
    sb.append("    sourceTeam: ").append(toIndentedString(sourceTeam)).append("\n");
    sb.append("    subscribed: ").append(toIndentedString(subscribed)).append("\n");
    sb.append("    subtype: ").append(toIndentedString(subtype)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    threadTs: ").append(toIndentedString(threadTs)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unreadCount: ").append(toIndentedString(unreadCount)).append("\n");
    sb.append("    upload: ").append(toIndentedString(upload)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userProfile: ").append(toIndentedString(userProfile)).append("\n");
    sb.append("    userTeam: ").append(toIndentedString(userTeam)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
