/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RemindersAddSchemaReminder
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class RemindersAddSchemaReminder {
  @JsonProperty("complete_ts")
  private Integer completeTs = null;

  @JsonProperty("creator")
  private String creator = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("recurring")
  private Boolean recurring = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("time")
  private Integer time = null;

  @JsonProperty("user")
  private String user = null;

  public RemindersAddSchemaReminder completeTs(Integer completeTs) {
    this.completeTs = completeTs;
    return this;
  }

   /**
   * Get completeTs
   * @return completeTs
  **/
  public Integer getCompleteTs() {
    return completeTs;
  }

  public void setCompleteTs(Integer completeTs) {
    this.completeTs = completeTs;
  }

  public RemindersAddSchemaReminder creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public RemindersAddSchemaReminder id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RemindersAddSchemaReminder recurring(Boolean recurring) {
    this.recurring = recurring;
    return this;
  }

   /**
   * Get recurring
   * @return recurring
  **/
  public Boolean isRecurring() {
    return recurring;
  }

  public void setRecurring(Boolean recurring) {
    this.recurring = recurring;
  }

  public RemindersAddSchemaReminder text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public RemindersAddSchemaReminder time(Integer time) {
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  public Integer getTime() {
    return time;
  }

  public void setTime(Integer time) {
    this.time = time;
  }

  public RemindersAddSchemaReminder user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemindersAddSchemaReminder remindersAddSchemaReminder = (RemindersAddSchemaReminder) o;
    return Objects.equals(this.completeTs, remindersAddSchemaReminder.completeTs) &&
        Objects.equals(this.creator, remindersAddSchemaReminder.creator) &&
        Objects.equals(this.id, remindersAddSchemaReminder.id) &&
        Objects.equals(this.recurring, remindersAddSchemaReminder.recurring) &&
        Objects.equals(this.text, remindersAddSchemaReminder.text) &&
        Objects.equals(this.time, remindersAddSchemaReminder.time) &&
        Objects.equals(this.user, remindersAddSchemaReminder.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completeTs, creator, id, recurring, text, time, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemindersAddSchemaReminder {\n");
    
    sb.append("    completeTs: ").append(toIndentedString(completeTs)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
