/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * ResourcesInInfoFromAppsPermissionsInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class ResourcesInInfoFromAppsPermissionsInfo {
  @JsonProperty("excluded_ids")
  private List<Object> excludedIds = null;

  @JsonProperty("ids")
  private List<Object> ids = new ArrayList<>();

  @JsonProperty("wildcard")
  private Boolean wildcard = null;

  public ResourcesInInfoFromAppsPermissionsInfo excludedIds(List<Object> excludedIds) {
    this.excludedIds = excludedIds;
    return this;
  }

  public ResourcesInInfoFromAppsPermissionsInfo addExcludedIdsItem(Object excludedIdsItem) {
    if (this.excludedIds == null) {
      this.excludedIds = new ArrayList<>();
    }
    this.excludedIds.add(excludedIdsItem);
    return this;
  }

   /**
   * Get excludedIds
   * @return excludedIds
  **/
  public List<Object> getExcludedIds() {
    return excludedIds;
  }

  public void setExcludedIds(List<Object> excludedIds) {
    this.excludedIds = excludedIds;
  }

  public ResourcesInInfoFromAppsPermissionsInfo ids(List<Object> ids) {
    this.ids = ids;
    return this;
  }

  public ResourcesInInfoFromAppsPermissionsInfo addIdsItem(Object idsItem) {
    this.ids.add(idsItem);
    return this;
  }

   /**
   * Get ids
   * @return ids
  **/
  public List<Object> getIds() {
    return ids;
  }

  public void setIds(List<Object> ids) {
    this.ids = ids;
  }

  public ResourcesInInfoFromAppsPermissionsInfo wildcard(Boolean wildcard) {
    this.wildcard = wildcard;
    return this;
  }

   /**
   * Get wildcard
   * @return wildcard
  **/
  public Boolean isWildcard() {
    return wildcard;
  }

  public void setWildcard(Boolean wildcard) {
    this.wildcard = wildcard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourcesInInfoFromAppsPermissionsInfo resourcesInInfoFromAppsPermissionsInfo = (ResourcesInInfoFromAppsPermissionsInfo) o;
    return Objects.equals(this.excludedIds, resourcesInInfoFromAppsPermissionsInfo.excludedIds) &&
        Objects.equals(this.ids, resourcesInInfoFromAppsPermissionsInfo.ids) &&
        Objects.equals(this.wildcard, resourcesInInfoFromAppsPermissionsInfo.wildcard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(excludedIds, ids, wildcard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourcesInInfoFromAppsPermissionsInfo {\n");
    
    sb.append("    excludedIds: ").append(toIndentedString(excludedIds)).append("\n");
    sb.append("    ids: ").append(toIndentedString(ids)).append("\n");
    sb.append("    wildcard: ").append(toIndentedString(wildcard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
