/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * StarsRemoveBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class StarsRemoveBody1 {
  @JsonProperty("channel")
  private String channel = null;

  @JsonProperty("file")
  private String file = null;

  @JsonProperty("file_comment")
  private String fileComment = null;

  @JsonProperty("timestamp")
  private String timestamp = null;

  public StarsRemoveBody1 channel(String channel) {
    this.channel = channel;
    return this;
  }

   /**
   * Channel to remove star from, or channel where the message to remove star from was posted (used with &#x60;timestamp&#x60;).
   * @return channel
  **/
  public String getChannel() {
    return channel;
  }

  public void setChannel(String channel) {
    this.channel = channel;
  }

  public StarsRemoveBody1 file(String file) {
    this.file = file;
    return this;
  }

   /**
   * File to remove star from.
   * @return file
  **/
  public String getFile() {
    return file;
  }

  public void setFile(String file) {
    this.file = file;
  }

  public StarsRemoveBody1 fileComment(String fileComment) {
    this.fileComment = fileComment;
    return this;
  }

   /**
   * File comment to remove star from.
   * @return fileComment
  **/
  public String getFileComment() {
    return fileComment;
  }

  public void setFileComment(String fileComment) {
    this.fileComment = fileComment;
  }

  public StarsRemoveBody1 timestamp(String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Timestamp of the message to remove star from.
   * @return timestamp
  **/
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StarsRemoveBody1 starsRemoveBody1 = (StarsRemoveBody1) o;
    return Objects.equals(this.channel, starsRemoveBody1.channel) &&
        Objects.equals(this.file, starsRemoveBody1.file) &&
        Objects.equals(this.fileComment, starsRemoveBody1.fileComment) &&
        Objects.equals(this.timestamp, starsRemoveBody1.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, file, fileComment, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StarsRemoveBody1 {\n");
    
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    fileComment: ").append(toIndentedString(fileComment)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
