/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.ExternalOrgMigrations;
import com.slack.api.client.ObjsTeamIcon;
import com.slack.api.client.ObjsTeamPrimaryOwner;
import com.slack.api.client.ObjsTeamSsoProvider;

/**
 * TeamObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class TeamObject {
  @JsonProperty("archived")
  private Boolean archived = null;

  @JsonProperty("avatar_base_url")
  private String avatarBaseUrl = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("date_create")
  private Integer dateCreate = null;

  @JsonProperty("deleted")
  private Boolean deleted = null;

  @JsonProperty("discoverable")
  private Object discoverable = null;

  @JsonProperty("domain")
  private String domain = null;

  @JsonProperty("email_domain")
  private String emailDomain = null;

  @JsonProperty("enterprise_id")
  private String enterpriseId = null;

  @JsonProperty("enterprise_name")
  private String enterpriseName = null;

  @JsonProperty("external_org_migrations")
  private ExternalOrgMigrations externalOrgMigrations = null;

  @JsonProperty("has_compliance_export")
  private Boolean hasComplianceExport = null;

  @JsonProperty("icon")
  private ObjsTeamIcon icon = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("is_assigned")
  private Boolean isAssigned = null;

  @JsonProperty("is_enterprise")
  private Integer isEnterprise = null;

  @JsonProperty("is_over_storage_limit")
  private Boolean isOverStorageLimit = null;

  @JsonProperty("limit_ts")
  private Integer limitTs = null;

  @JsonProperty("locale")
  private String locale = null;

  @JsonProperty("messages_count")
  private Integer messagesCount = null;

  @JsonProperty("msg_edit_window_mins")
  private Integer msgEditWindowMins = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("over_integrations_limit")
  private Boolean overIntegrationsLimit = null;

  @JsonProperty("over_storage_limit")
  private Boolean overStorageLimit = null;

  @JsonProperty("pay_prod_cur")
  private String payProdCur = null;

  /**
   * Gets or Sets plan
   */
  public enum PlanEnum {
    EMPTY(""),
    STD("std"),
    PLUS("plus"),
    COMPLIANCE("compliance"),
    ENTERPRISE("enterprise");

    private String value;

    PlanEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PlanEnum fromValue(String input) {
      for (PlanEnum b : PlanEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("plan")
  private PlanEnum plan = null;

  @JsonProperty("primary_owner")
  private ObjsTeamPrimaryOwner primaryOwner = null;

  @JsonProperty("sso_provider")
  private ObjsTeamSsoProvider ssoProvider = null;

  public TeamObject archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * Get archived
   * @return archived
  **/
  public Boolean isArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public TeamObject avatarBaseUrl(String avatarBaseUrl) {
    this.avatarBaseUrl = avatarBaseUrl;
    return this;
  }

   /**
   * Get avatarBaseUrl
   * @return avatarBaseUrl
  **/
  public String getAvatarBaseUrl() {
    return avatarBaseUrl;
  }

  public void setAvatarBaseUrl(String avatarBaseUrl) {
    this.avatarBaseUrl = avatarBaseUrl;
  }

  public TeamObject created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public TeamObject dateCreate(Integer dateCreate) {
    this.dateCreate = dateCreate;
    return this;
  }

   /**
   * Get dateCreate
   * @return dateCreate
  **/
  public Integer getDateCreate() {
    return dateCreate;
  }

  public void setDateCreate(Integer dateCreate) {
    this.dateCreate = dateCreate;
  }

  public TeamObject deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public TeamObject discoverable(Object discoverable) {
    this.discoverable = discoverable;
    return this;
  }

   /**
   * Get discoverable
   * @return discoverable
  **/
  public Object getDiscoverable() {
    return discoverable;
  }

  public void setDiscoverable(Object discoverable) {
    this.discoverable = discoverable;
  }

  public TeamObject domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public TeamObject emailDomain(String emailDomain) {
    this.emailDomain = emailDomain;
    return this;
  }

   /**
   * Get emailDomain
   * @return emailDomain
  **/
  public String getEmailDomain() {
    return emailDomain;
  }

  public void setEmailDomain(String emailDomain) {
    this.emailDomain = emailDomain;
  }

  public TeamObject enterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId;
    return this;
  }

   /**
   * Get enterpriseId
   * @return enterpriseId
  **/
  public String getEnterpriseId() {
    return enterpriseId;
  }

  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId;
  }

  public TeamObject enterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
    return this;
  }

   /**
   * Get enterpriseName
   * @return enterpriseName
  **/
  public String getEnterpriseName() {
    return enterpriseName;
  }

  public void setEnterpriseName(String enterpriseName) {
    this.enterpriseName = enterpriseName;
  }

  public TeamObject externalOrgMigrations(ExternalOrgMigrations externalOrgMigrations) {
    this.externalOrgMigrations = externalOrgMigrations;
    return this;
  }

   /**
   * Get externalOrgMigrations
   * @return externalOrgMigrations
  **/
  public ExternalOrgMigrations getExternalOrgMigrations() {
    return externalOrgMigrations;
  }

  public void setExternalOrgMigrations(ExternalOrgMigrations externalOrgMigrations) {
    this.externalOrgMigrations = externalOrgMigrations;
  }

  public TeamObject hasComplianceExport(Boolean hasComplianceExport) {
    this.hasComplianceExport = hasComplianceExport;
    return this;
  }

   /**
   * Get hasComplianceExport
   * @return hasComplianceExport
  **/
  public Boolean isHasComplianceExport() {
    return hasComplianceExport;
  }

  public void setHasComplianceExport(Boolean hasComplianceExport) {
    this.hasComplianceExport = hasComplianceExport;
  }

  public TeamObject icon(ObjsTeamIcon icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  public ObjsTeamIcon getIcon() {
    return icon;
  }

  public void setIcon(ObjsTeamIcon icon) {
    this.icon = icon;
  }

  public TeamObject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TeamObject isAssigned(Boolean isAssigned) {
    this.isAssigned = isAssigned;
    return this;
  }

   /**
   * Get isAssigned
   * @return isAssigned
  **/
  public Boolean isIsAssigned() {
    return isAssigned;
  }

  public void setIsAssigned(Boolean isAssigned) {
    this.isAssigned = isAssigned;
  }

  public TeamObject isEnterprise(Integer isEnterprise) {
    this.isEnterprise = isEnterprise;
    return this;
  }

   /**
   * Get isEnterprise
   * @return isEnterprise
  **/
  public Integer getIsEnterprise() {
    return isEnterprise;
  }

  public void setIsEnterprise(Integer isEnterprise) {
    this.isEnterprise = isEnterprise;
  }

  public TeamObject isOverStorageLimit(Boolean isOverStorageLimit) {
    this.isOverStorageLimit = isOverStorageLimit;
    return this;
  }

   /**
   * Get isOverStorageLimit
   * @return isOverStorageLimit
  **/
  public Boolean isIsOverStorageLimit() {
    return isOverStorageLimit;
  }

  public void setIsOverStorageLimit(Boolean isOverStorageLimit) {
    this.isOverStorageLimit = isOverStorageLimit;
  }

  public TeamObject limitTs(Integer limitTs) {
    this.limitTs = limitTs;
    return this;
  }

   /**
   * Get limitTs
   * @return limitTs
  **/
  public Integer getLimitTs() {
    return limitTs;
  }

  public void setLimitTs(Integer limitTs) {
    this.limitTs = limitTs;
  }

  public TeamObject locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Get locale
   * @return locale
  **/
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public TeamObject messagesCount(Integer messagesCount) {
    this.messagesCount = messagesCount;
    return this;
  }

   /**
   * Get messagesCount
   * @return messagesCount
  **/
  public Integer getMessagesCount() {
    return messagesCount;
  }

  public void setMessagesCount(Integer messagesCount) {
    this.messagesCount = messagesCount;
  }

  public TeamObject msgEditWindowMins(Integer msgEditWindowMins) {
    this.msgEditWindowMins = msgEditWindowMins;
    return this;
  }

   /**
   * Get msgEditWindowMins
   * @return msgEditWindowMins
  **/
  public Integer getMsgEditWindowMins() {
    return msgEditWindowMins;
  }

  public void setMsgEditWindowMins(Integer msgEditWindowMins) {
    this.msgEditWindowMins = msgEditWindowMins;
  }

  public TeamObject name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TeamObject overIntegrationsLimit(Boolean overIntegrationsLimit) {
    this.overIntegrationsLimit = overIntegrationsLimit;
    return this;
  }

   /**
   * Get overIntegrationsLimit
   * @return overIntegrationsLimit
  **/
  public Boolean isOverIntegrationsLimit() {
    return overIntegrationsLimit;
  }

  public void setOverIntegrationsLimit(Boolean overIntegrationsLimit) {
    this.overIntegrationsLimit = overIntegrationsLimit;
  }

  public TeamObject overStorageLimit(Boolean overStorageLimit) {
    this.overStorageLimit = overStorageLimit;
    return this;
  }

   /**
   * Get overStorageLimit
   * @return overStorageLimit
  **/
  public Boolean isOverStorageLimit() {
    return overStorageLimit;
  }

  public void setOverStorageLimit(Boolean overStorageLimit) {
    this.overStorageLimit = overStorageLimit;
  }

  public TeamObject payProdCur(String payProdCur) {
    this.payProdCur = payProdCur;
    return this;
  }

   /**
   * Get payProdCur
   * @return payProdCur
  **/
  public String getPayProdCur() {
    return payProdCur;
  }

  public void setPayProdCur(String payProdCur) {
    this.payProdCur = payProdCur;
  }

  public TeamObject plan(PlanEnum plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  public PlanEnum getPlan() {
    return plan;
  }

  public void setPlan(PlanEnum plan) {
    this.plan = plan;
  }

  public TeamObject primaryOwner(ObjsTeamPrimaryOwner primaryOwner) {
    this.primaryOwner = primaryOwner;
    return this;
  }

   /**
   * Get primaryOwner
   * @return primaryOwner
  **/
  public ObjsTeamPrimaryOwner getPrimaryOwner() {
    return primaryOwner;
  }

  public void setPrimaryOwner(ObjsTeamPrimaryOwner primaryOwner) {
    this.primaryOwner = primaryOwner;
  }

  public TeamObject ssoProvider(ObjsTeamSsoProvider ssoProvider) {
    this.ssoProvider = ssoProvider;
    return this;
  }

   /**
   * Get ssoProvider
   * @return ssoProvider
  **/
  public ObjsTeamSsoProvider getSsoProvider() {
    return ssoProvider;
  }

  public void setSsoProvider(ObjsTeamSsoProvider ssoProvider) {
    this.ssoProvider = ssoProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamObject teamObject = (TeamObject) o;
    return Objects.equals(this.archived, teamObject.archived) &&
        Objects.equals(this.avatarBaseUrl, teamObject.avatarBaseUrl) &&
        Objects.equals(this.created, teamObject.created) &&
        Objects.equals(this.dateCreate, teamObject.dateCreate) &&
        Objects.equals(this.deleted, teamObject.deleted) &&
        Objects.equals(this.discoverable, teamObject.discoverable) &&
        Objects.equals(this.domain, teamObject.domain) &&
        Objects.equals(this.emailDomain, teamObject.emailDomain) &&
        Objects.equals(this.enterpriseId, teamObject.enterpriseId) &&
        Objects.equals(this.enterpriseName, teamObject.enterpriseName) &&
        Objects.equals(this.externalOrgMigrations, teamObject.externalOrgMigrations) &&
        Objects.equals(this.hasComplianceExport, teamObject.hasComplianceExport) &&
        Objects.equals(this.icon, teamObject.icon) &&
        Objects.equals(this.id, teamObject.id) &&
        Objects.equals(this.isAssigned, teamObject.isAssigned) &&
        Objects.equals(this.isEnterprise, teamObject.isEnterprise) &&
        Objects.equals(this.isOverStorageLimit, teamObject.isOverStorageLimit) &&
        Objects.equals(this.limitTs, teamObject.limitTs) &&
        Objects.equals(this.locale, teamObject.locale) &&
        Objects.equals(this.messagesCount, teamObject.messagesCount) &&
        Objects.equals(this.msgEditWindowMins, teamObject.msgEditWindowMins) &&
        Objects.equals(this.name, teamObject.name) &&
        Objects.equals(this.overIntegrationsLimit, teamObject.overIntegrationsLimit) &&
        Objects.equals(this.overStorageLimit, teamObject.overStorageLimit) &&
        Objects.equals(this.payProdCur, teamObject.payProdCur) &&
        Objects.equals(this.plan, teamObject.plan) &&
        Objects.equals(this.primaryOwner, teamObject.primaryOwner) &&
        Objects.equals(this.ssoProvider, teamObject.ssoProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archived, avatarBaseUrl, created, dateCreate, deleted, discoverable, domain, emailDomain, enterpriseId, enterpriseName, externalOrgMigrations, hasComplianceExport, icon, id, isAssigned, isEnterprise, isOverStorageLimit, limitTs, locale, messagesCount, msgEditWindowMins, name, overIntegrationsLimit, overStorageLimit, payProdCur, plan, primaryOwner, ssoProvider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamObject {\n");
    
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    avatarBaseUrl: ").append(toIndentedString(avatarBaseUrl)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    dateCreate: ").append(toIndentedString(dateCreate)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    discoverable: ").append(toIndentedString(discoverable)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    emailDomain: ").append(toIndentedString(emailDomain)).append("\n");
    sb.append("    enterpriseId: ").append(toIndentedString(enterpriseId)).append("\n");
    sb.append("    enterpriseName: ").append(toIndentedString(enterpriseName)).append("\n");
    sb.append("    externalOrgMigrations: ").append(toIndentedString(externalOrgMigrations)).append("\n");
    sb.append("    hasComplianceExport: ").append(toIndentedString(hasComplianceExport)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isAssigned: ").append(toIndentedString(isAssigned)).append("\n");
    sb.append("    isEnterprise: ").append(toIndentedString(isEnterprise)).append("\n");
    sb.append("    isOverStorageLimit: ").append(toIndentedString(isOverStorageLimit)).append("\n");
    sb.append("    limitTs: ").append(toIndentedString(limitTs)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    messagesCount: ").append(toIndentedString(messagesCount)).append("\n");
    sb.append("    msgEditWindowMins: ").append(toIndentedString(msgEditWindowMins)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    overIntegrationsLimit: ").append(toIndentedString(overIntegrationsLimit)).append("\n");
    sb.append("    overStorageLimit: ").append(toIndentedString(overStorageLimit)).append("\n");
    sb.append("    payProdCur: ").append(toIndentedString(payProdCur)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    primaryOwner: ").append(toIndentedString(primaryOwner)).append("\n");
    sb.append("    ssoProvider: ").append(toIndentedString(ssoProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
