/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.slack.api.client.PagingObject;

import java.util.ArrayList;
import java.util.List;
/**
 * Schema for successful response from team.integrationLogs method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class TeamIntegrationLogsSchema {
  @JsonProperty("logs")
  private List<Object> logs = new ArrayList<>();

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("paging")
  private PagingObject paging = null;

  public TeamIntegrationLogsSchema logs(List<Object> logs) {
    this.logs = logs;
    return this;
  }

  public TeamIntegrationLogsSchema addLogsItem(Object logsItem) {
    this.logs.add(logsItem);
    return this;
  }

   /**
   * Get logs
   * @return logs
  **/
  public List<Object> getLogs() {
    return logs;
  }

  public void setLogs(List<Object> logs) {
    this.logs = logs;
  }

  public TeamIntegrationLogsSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public TeamIntegrationLogsSchema paging(PagingObject paging) {
    this.paging = paging;
    return this;
  }

   /**
   * Get paging
   * @return paging
  **/
  public PagingObject getPaging() {
    return paging;
  }

  public void setPaging(PagingObject paging) {
    this.paging = paging;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamIntegrationLogsSchema teamIntegrationLogsSchema = (TeamIntegrationLogsSchema) o;
    return Objects.equals(this.logs, teamIntegrationLogsSchema.logs) &&
        Objects.equals(this.ok, teamIntegrationLogsSchema.ok) &&
        Objects.equals(this.paging, teamIntegrationLogsSchema.paging);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logs, ok, paging);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamIntegrationLogsSchema {\n");
    
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
