/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * Schema for successful response from users.list method
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class UsersListSchema {
  @JsonProperty("cache_ts")
  private Integer cacheTs = null;

  @JsonProperty("members")
  private List<List> members = new ArrayList<>();

  @JsonProperty("ok")
  private Boolean ok = null;

  @JsonProperty("response_metadata")
  private List responseMetadata = null;

  public UsersListSchema cacheTs(Integer cacheTs) {
    this.cacheTs = cacheTs;
    return this;
  }

   /**
   * Get cacheTs
   * @return cacheTs
  **/
  public Integer getCacheTs() {
    return cacheTs;
  }

  public void setCacheTs(Integer cacheTs) {
    this.cacheTs = cacheTs;
  }

  public UsersListSchema members(List<List> members) {
    this.members = members;
    return this;
  }

  public UsersListSchema addMembersItem(List membersItem) {
    this.members.add(membersItem);
    return this;
  }

   /**
   * Get members
   * @return members
  **/
  public List<List> getMembers() {
    return members;
  }

  public void setMembers(List<List> members) {
    this.members = members;
  }

  public UsersListSchema ok(Boolean ok) {
    this.ok = ok;
    return this;
  }

   /**
   * Get ok
   * @return ok
  **/
  public Boolean isOk() {
    return ok;
  }

  public void setOk(Boolean ok) {
    this.ok = ok;
  }

  public UsersListSchema responseMetadata(List responseMetadata) {
    this.responseMetadata = responseMetadata;
    return this;
  }

   /**
   * Get responseMetadata
   * @return responseMetadata
  **/
  public List getResponseMetadata() {
    return responseMetadata;
  }

  public void setResponseMetadata(List responseMetadata) {
    this.responseMetadata = responseMetadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersListSchema usersListSchema = (UsersListSchema) o;
    return Objects.equals(this.cacheTs, usersListSchema.cacheTs) &&
        Objects.equals(this.members, usersListSchema.members) &&
        Objects.equals(this.ok, usersListSchema.ok) &&
        Objects.equals(this.responseMetadata, usersListSchema.responseMetadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cacheTs, members, ok, responseMetadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersListSchema {\n");
    
    sb.append("    cacheTs: ").append(toIndentedString(cacheTs)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    responseMetadata: ").append(toIndentedString(responseMetadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
