/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UserProfileObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class UserProfileObject {
  @JsonProperty("always_active")
  private Boolean alwaysActive = null;

  @JsonProperty("api_app_id")
  private String apiAppId = null;

  @JsonProperty("avatar_hash")
  private String avatarHash = null;

  @JsonProperty("bot_id")
  private String botId = null;

  @JsonProperty("display_name")
  private String displayName = null;

  @JsonProperty("display_name_normalized")
  private String displayNameNormalized = null;

  @JsonProperty("is_app_user")
  private Boolean isAppUser = null;

  @JsonProperty("is_custom_image")
  private Boolean isCustomImage = null;

  @JsonProperty("last_avatar_image_hash")
  private String lastAvatarImageHash = null;

  @JsonProperty("memberships_count")
  private Integer membershipsCount = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("pronouns")
  private String pronouns = null;

  @JsonProperty("real_name")
  private String realName = null;

  @JsonProperty("real_name_normalized")
  private String realNameNormalized = null;

  @JsonProperty("skype")
  private String skype = null;

  @JsonProperty("status_default_emoji")
  private String statusDefaultEmoji = null;

  @JsonProperty("status_default_text")
  private String statusDefaultText = null;

  @JsonProperty("status_emoji")
  private String statusEmoji = null;

  @JsonProperty("status_expiration")
  private Integer statusExpiration = null;

  @JsonProperty("status_text")
  private String statusText = null;

  @JsonProperty("team")
  private String team = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("updated")
  private Integer updated = null;

  @JsonProperty("user_id")
  private String userId = null;

  public UserProfileObject alwaysActive(Boolean alwaysActive) {
    this.alwaysActive = alwaysActive;
    return this;
  }

   /**
   * Get alwaysActive
   * @return alwaysActive
  **/
  public Boolean isAlwaysActive() {
    return alwaysActive;
  }

  public void setAlwaysActive(Boolean alwaysActive) {
    this.alwaysActive = alwaysActive;
  }

  public UserProfileObject apiAppId(String apiAppId) {
    this.apiAppId = apiAppId;
    return this;
  }

   /**
   * Get apiAppId
   * @return apiAppId
  **/
  public String getApiAppId() {
    return apiAppId;
  }

  public void setApiAppId(String apiAppId) {
    this.apiAppId = apiAppId;
  }

  public UserProfileObject avatarHash(String avatarHash) {
    this.avatarHash = avatarHash;
    return this;
  }

   /**
   * Get avatarHash
   * @return avatarHash
  **/
  public String getAvatarHash() {
    return avatarHash;
  }

  public void setAvatarHash(String avatarHash) {
    this.avatarHash = avatarHash;
  }

  public UserProfileObject botId(String botId) {
    this.botId = botId;
    return this;
  }

   /**
   * Get botId
   * @return botId
  **/
  public String getBotId() {
    return botId;
  }

  public void setBotId(String botId) {
    this.botId = botId;
  }

  public UserProfileObject displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public UserProfileObject displayNameNormalized(String displayNameNormalized) {
    this.displayNameNormalized = displayNameNormalized;
    return this;
  }

   /**
   * Get displayNameNormalized
   * @return displayNameNormalized
  **/
  public String getDisplayNameNormalized() {
    return displayNameNormalized;
  }

  public void setDisplayNameNormalized(String displayNameNormalized) {
    this.displayNameNormalized = displayNameNormalized;
  }

  public UserProfileObject isAppUser(Boolean isAppUser) {
    this.isAppUser = isAppUser;
    return this;
  }

   /**
   * Get isAppUser
   * @return isAppUser
  **/
  public Boolean isIsAppUser() {
    return isAppUser;
  }

  public void setIsAppUser(Boolean isAppUser) {
    this.isAppUser = isAppUser;
  }

  public UserProfileObject isCustomImage(Boolean isCustomImage) {
    this.isCustomImage = isCustomImage;
    return this;
  }

   /**
   * Get isCustomImage
   * @return isCustomImage
  **/
  public Boolean isIsCustomImage() {
    return isCustomImage;
  }

  public void setIsCustomImage(Boolean isCustomImage) {
    this.isCustomImage = isCustomImage;
  }

  public UserProfileObject lastAvatarImageHash(String lastAvatarImageHash) {
    this.lastAvatarImageHash = lastAvatarImageHash;
    return this;
  }

   /**
   * Get lastAvatarImageHash
   * @return lastAvatarImageHash
  **/
  public String getLastAvatarImageHash() {
    return lastAvatarImageHash;
  }

  public void setLastAvatarImageHash(String lastAvatarImageHash) {
    this.lastAvatarImageHash = lastAvatarImageHash;
  }

  public UserProfileObject membershipsCount(Integer membershipsCount) {
    this.membershipsCount = membershipsCount;
    return this;
  }

   /**
   * Get membershipsCount
   * @return membershipsCount
  **/
  public Integer getMembershipsCount() {
    return membershipsCount;
  }

  public void setMembershipsCount(Integer membershipsCount) {
    this.membershipsCount = membershipsCount;
  }

  public UserProfileObject phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public UserProfileObject pronouns(String pronouns) {
    this.pronouns = pronouns;
    return this;
  }

   /**
   * Get pronouns
   * @return pronouns
  **/
  public String getPronouns() {
    return pronouns;
  }

  public void setPronouns(String pronouns) {
    this.pronouns = pronouns;
  }

  public UserProfileObject realName(String realName) {
    this.realName = realName;
    return this;
  }

   /**
   * Get realName
   * @return realName
  **/
  public String getRealName() {
    return realName;
  }

  public void setRealName(String realName) {
    this.realName = realName;
  }

  public UserProfileObject realNameNormalized(String realNameNormalized) {
    this.realNameNormalized = realNameNormalized;
    return this;
  }

   /**
   * Get realNameNormalized
   * @return realNameNormalized
  **/
  public String getRealNameNormalized() {
    return realNameNormalized;
  }

  public void setRealNameNormalized(String realNameNormalized) {
    this.realNameNormalized = realNameNormalized;
  }

  public UserProfileObject skype(String skype) {
    this.skype = skype;
    return this;
  }

   /**
   * Get skype
   * @return skype
  **/
  public String getSkype() {
    return skype;
  }

  public void setSkype(String skype) {
    this.skype = skype;
  }

  public UserProfileObject statusDefaultEmoji(String statusDefaultEmoji) {
    this.statusDefaultEmoji = statusDefaultEmoji;
    return this;
  }

   /**
   * Get statusDefaultEmoji
   * @return statusDefaultEmoji
  **/
  public String getStatusDefaultEmoji() {
    return statusDefaultEmoji;
  }

  public void setStatusDefaultEmoji(String statusDefaultEmoji) {
    this.statusDefaultEmoji = statusDefaultEmoji;
  }

  public UserProfileObject statusDefaultText(String statusDefaultText) {
    this.statusDefaultText = statusDefaultText;
    return this;
  }

   /**
   * Get statusDefaultText
   * @return statusDefaultText
  **/
  public String getStatusDefaultText() {
    return statusDefaultText;
  }

  public void setStatusDefaultText(String statusDefaultText) {
    this.statusDefaultText = statusDefaultText;
  }

  public UserProfileObject statusEmoji(String statusEmoji) {
    this.statusEmoji = statusEmoji;
    return this;
  }

   /**
   * Get statusEmoji
   * @return statusEmoji
  **/
  public String getStatusEmoji() {
    return statusEmoji;
  }

  public void setStatusEmoji(String statusEmoji) {
    this.statusEmoji = statusEmoji;
  }

  public UserProfileObject statusExpiration(Integer statusExpiration) {
    this.statusExpiration = statusExpiration;
    return this;
  }

   /**
   * Get statusExpiration
   * @return statusExpiration
  **/
  public Integer getStatusExpiration() {
    return statusExpiration;
  }

  public void setStatusExpiration(Integer statusExpiration) {
    this.statusExpiration = statusExpiration;
  }

  public UserProfileObject statusText(String statusText) {
    this.statusText = statusText;
    return this;
  }

   /**
   * Get statusText
   * @return statusText
  **/
  public String getStatusText() {
    return statusText;
  }

  public void setStatusText(String statusText) {
    this.statusText = statusText;
  }

  public UserProfileObject team(String team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  public String getTeam() {
    return team;
  }

  public void setTeam(String team) {
    this.team = team;
  }

  public UserProfileObject title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public UserProfileObject updated(Integer updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  public Integer getUpdated() {
    return updated;
  }

  public void setUpdated(Integer updated) {
    this.updated = updated;
  }

  public UserProfileObject userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileObject userProfileObject = (UserProfileObject) o;
    return Objects.equals(this.alwaysActive, userProfileObject.alwaysActive) &&
        Objects.equals(this.apiAppId, userProfileObject.apiAppId) &&
        Objects.equals(this.avatarHash, userProfileObject.avatarHash) &&
        Objects.equals(this.botId, userProfileObject.botId) &&
        Objects.equals(this.displayName, userProfileObject.displayName) &&
        Objects.equals(this.displayNameNormalized, userProfileObject.displayNameNormalized) &&
        Objects.equals(this.isAppUser, userProfileObject.isAppUser) &&
        Objects.equals(this.isCustomImage, userProfileObject.isCustomImage) &&
        Objects.equals(this.lastAvatarImageHash, userProfileObject.lastAvatarImageHash) &&
        Objects.equals(this.membershipsCount, userProfileObject.membershipsCount) &&
        Objects.equals(this.phone, userProfileObject.phone) &&
        Objects.equals(this.pronouns, userProfileObject.pronouns) &&
        Objects.equals(this.realName, userProfileObject.realName) &&
        Objects.equals(this.realNameNormalized, userProfileObject.realNameNormalized) &&
        Objects.equals(this.skype, userProfileObject.skype) &&
        Objects.equals(this.statusDefaultEmoji, userProfileObject.statusDefaultEmoji) &&
        Objects.equals(this.statusDefaultText, userProfileObject.statusDefaultText) &&
        Objects.equals(this.statusEmoji, userProfileObject.statusEmoji) &&
        Objects.equals(this.statusExpiration, userProfileObject.statusExpiration) &&
        Objects.equals(this.statusText, userProfileObject.statusText) &&
        Objects.equals(this.team, userProfileObject.team) &&
        Objects.equals(this.title, userProfileObject.title) &&
        Objects.equals(this.updated, userProfileObject.updated) &&
        Objects.equals(this.userId, userProfileObject.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alwaysActive, apiAppId, avatarHash, botId, displayName, displayNameNormalized, isAppUser, isCustomImage, lastAvatarImageHash, membershipsCount, phone, pronouns, realName, realNameNormalized, skype, statusDefaultEmoji, statusDefaultText, statusEmoji, statusExpiration, statusText, team, title, updated, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileObject {\n");
    
    sb.append("    alwaysActive: ").append(toIndentedString(alwaysActive)).append("\n");
    sb.append("    apiAppId: ").append(toIndentedString(apiAppId)).append("\n");
    sb.append("    avatarHash: ").append(toIndentedString(avatarHash)).append("\n");
    sb.append("    botId: ").append(toIndentedString(botId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    displayNameNormalized: ").append(toIndentedString(displayNameNormalized)).append("\n");
    sb.append("    isAppUser: ").append(toIndentedString(isAppUser)).append("\n");
    sb.append("    isCustomImage: ").append(toIndentedString(isCustomImage)).append("\n");
    sb.append("    lastAvatarImageHash: ").append(toIndentedString(lastAvatarImageHash)).append("\n");
    sb.append("    membershipsCount: ").append(toIndentedString(membershipsCount)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    pronouns: ").append(toIndentedString(pronouns)).append("\n");
    sb.append("    realName: ").append(toIndentedString(realName)).append("\n");
    sb.append("    realNameNormalized: ").append(toIndentedString(realNameNormalized)).append("\n");
    sb.append("    skype: ").append(toIndentedString(skype)).append("\n");
    sb.append("    statusDefaultEmoji: ").append(toIndentedString(statusDefaultEmoji)).append("\n");
    sb.append("    statusDefaultText: ").append(toIndentedString(statusDefaultText)).append("\n");
    sb.append("    statusEmoji: ").append(toIndentedString(statusEmoji)).append("\n");
    sb.append("    statusExpiration: ").append(toIndentedString(statusExpiration)).append("\n");
    sb.append("    statusText: ").append(toIndentedString(statusText)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
