/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsergroupsCreateBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class UsergroupsCreateBody {
  @JsonProperty("channels")
  private String channels = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("handle")
  private String handle = null;

  @JsonProperty("include_count")
  private Boolean includeCount = null;

  @JsonProperty("name")
  private String name = null;

  public UsergroupsCreateBody channels(String channels) {
    this.channels = channels;
    return this;
  }

   /**
   * A comma separated string of encoded channel IDs for which the User Group uses as a default.
   * @return channels
  **/
  public String getChannels() {
    return channels;
  }

  public void setChannels(String channels) {
    this.channels = channels;
  }

  public UsergroupsCreateBody description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A short description of the User Group.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UsergroupsCreateBody handle(String handle) {
    this.handle = handle;
    return this;
  }

   /**
   * A mention handle. Must be unique among channels, users and User Groups.
   * @return handle
  **/
  public String getHandle() {
    return handle;
  }

  public void setHandle(String handle) {
    this.handle = handle;
  }

  public UsergroupsCreateBody includeCount(Boolean includeCount) {
    this.includeCount = includeCount;
    return this;
  }

   /**
   * Include the number of users in each User Group.
   * @return includeCount
  **/
  public Boolean isIncludeCount() {
    return includeCount;
  }

  public void setIncludeCount(Boolean includeCount) {
    this.includeCount = includeCount;
  }

  public UsergroupsCreateBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A name for the User Group. Must be unique among User Groups.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsergroupsCreateBody usergroupsCreateBody = (UsergroupsCreateBody) o;
    return Objects.equals(this.channels, usergroupsCreateBody.channels) &&
        Objects.equals(this.description, usergroupsCreateBody.description) &&
        Objects.equals(this.handle, usergroupsCreateBody.handle) &&
        Objects.equals(this.includeCount, usergroupsCreateBody.includeCount) &&
        Objects.equals(this.name, usergroupsCreateBody.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channels, description, handle, includeCount, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsergroupsCreateBody {\n");
    
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    handle: ").append(toIndentedString(handle)).append("\n");
    sb.append("    includeCount: ").append(toIndentedString(includeCount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
