/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * OpenAPI spec version: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.slack.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UsergroupsUsersUpdateBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-05-19T10:50:20.722915200+07:00[Asia/Bangkok]")

public class UsergroupsUsersUpdateBody {
  @JsonProperty("include_count")
  private Boolean includeCount = null;

  @JsonProperty("usergroup")
  private String usergroup = null;

  @JsonProperty("users")
  private String users = null;

  public UsergroupsUsersUpdateBody includeCount(Boolean includeCount) {
    this.includeCount = includeCount;
    return this;
  }

   /**
   * Include the number of users in the User Group.
   * @return includeCount
  **/
  public Boolean isIncludeCount() {
    return includeCount;
  }

  public void setIncludeCount(Boolean includeCount) {
    this.includeCount = includeCount;
  }

  public UsergroupsUsersUpdateBody usergroup(String usergroup) {
    this.usergroup = usergroup;
    return this;
  }

   /**
   * The encoded ID of the User Group to update.
   * @return usergroup
  **/
  public String getUsergroup() {
    return usergroup;
  }

  public void setUsergroup(String usergroup) {
    this.usergroup = usergroup;
  }

  public UsergroupsUsersUpdateBody users(String users) {
    this.users = users;
    return this;
  }

   /**
   * A comma separated string of encoded user IDs that represent the entire list of users for the User Group.
   * @return users
  **/
  public String getUsers() {
    return users;
  }

  public void setUsers(String users) {
    this.users = users;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsergroupsUsersUpdateBody usergroupsUsersUpdateBody = (UsergroupsUsersUpdateBody) o;
    return Objects.equals(this.includeCount, usergroupsUsersUpdateBody.includeCount) &&
        Objects.equals(this.usergroup, usergroupsUsersUpdateBody.usergroup) &&
        Objects.equals(this.users, usergroupsUsersUpdateBody.users);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeCount, usergroup, users);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsergroupsUsersUpdateBody {\n");
    
    sb.append("    includeCount: ").append(toIndentedString(includeCount)).append("\n");
    sb.append("    usergroup: ").append(toIndentedString(usergroup)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
