# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  com:
    axonivy:
      connector:
        slack:
          # the base url for Slack api
          baseUrl: https://slack.com/api
          notification:
            # enables the Slack notification for new tasks
            enabled: "true"
          # the token from Slack bot
          #[password]
          botToken: ${decrypt:}
          #[password]
          signingSecret: ${decrypt:}
